// Load settings from Storage or use defaults
var settings = Object.assign({}, require('Storage').readJSON("chronometer.settings.json", true) || {});

// Cantarell fonts. Bold for the clock, small for the date.
Graphics.prototype.setFontClock = function () {
    // Actual height 61 (63 - 3)
    // 2 BPP
    return this.setFontCustom(
        E.toString(require('heatshrink').decompress(atob('AH8AioQPh/9CB0D//0CJ1///ACBsL//8ER2/ER8HESE//9ACJ3/6CMPqDCjgQQPjfwB5sBRoIgO///ERtvCAIiMgwPCERggD//kKRQPDYBZSCAAP5OZgACyAgZKSBzE/xSKOaBSEwBzqgE/OZ0AgZSNEQhzLEQggNEQRzKNAoPOAH4AMtShB/SRLgzUD//0CBMLCAn//oQPCJIQHCJD2DAAv4YIwKC8oGBi2/AwPgCIt///+OokfCIPACAgIBHoxNB/xEGJw8PRww9BOI8vGgoYBHYpPDGghnB+AQHgQKFn63JFoJxDKwIzIGgKeEAopzGDgcHFAgAFn/8PIhWIK4QiDUgIQIRgIiVIqJoQRaKuQYwzRKeiB6BRhEfDYpXBIw6nB+gYGCIwQBGYo7BBAKfEDIJPGgIIB//lAwMFJoJyHYIIAHXA49BAAymIHwQAEKowACjYhOAAMGIZgAEtYPB/VQCBYAgn5hJRY63FABLrGGf4z/Gc3/CB0D/4AK+AiFABQi/ERIA/gNVBA0b/rcHNAgABt//6DcNl//EQ0PEQ0fQQIiFU4QHEg4HBEQ2/EQsBUoQiFHgIiFJgP0EIsLaIwHBCAwrDA4v8RI1/EQw7BCAxwB7YKEN4PACApwB+m/EQl//C9H/pQBKwtAXo+AEQrXHXoPgEQoIBCApNBHgIiG8BEGDIIiG/z6HOAIiMDwINBERkCWoZoM34eCRY69G6AiH36uEXoQcHaIpEB/ocDEQk/K4hEBYwQiFgKmCZwZECEQzABAwSaBIgRiHv4MCt5EEEQw0BAAhECEQ4GBAAZEDEQxBCAATWEEQxGCAAJVDERARDCAoiHMwXkBAoiHABEBqoQOAH4ADhLCDAA0VAoh/HOASCFh6iGeogiF/6bH34JFEQL5FAAM/ERH/LIoaCEQ/8CAkDBAP+LwxGGv48HBIWAFYoQHI4I0EgSCIHwXgM4n9WxEfOIkH//ACJG/FogFEgWqQwYcBK4ZWBHIn4ApKAEKIIcDAoI/Dh6aEDgsvPQhuEEQqFBEVl/DggiGNAcLDghoFBYLdJn4FEv5RDUQJLDVwooEKAIoFaIkvBYd/BYj0FgJADj/9FAYtBHIZXCDoIDB54dDLgpdB//+14UB34MCHIJWDGgQAC/wvB/MAt6WEN4YAC4BdBAAX9CAheCAAIbBCAf/oARFHgJPCGgIAC6AQFCIQsCWAIABTYgADjWoUgn/ZIYAKCIIQOQQJUGAHjHBeIgAK3/+CByiBERzXBER0LVoIiNg4QBERsCcIQiNB4PvERpmB+giNeIUPERkP//9GwIiLMwQUBERZmCwAiMbwP/6AiN3//+B8CERU/MwJaCERTeBMwIiMbwIdDERUDKoNAERhmC4AiNMwIcEERLeCYYgiIMwP8A4giIbwIbFERBmGERSrBbwIiPABLYCEQYAKEX4iJABDRJWw70JEX4ivAGkqoAKIgNV1TdCfoOADI2/dwnwfoQRFDIIAFBAYiFDIIiI/oiQ+giNl4EB4AiH1NUv4vCg//YQs//AECj5ADhY0FQQgdBTIcfGgoiE//gBQe/NIgiEj/8BQoXEEQa7GGgIiIv6FFP4QiGMQIQEAwJdDEQgbFFIwiDh4iFJgoiFMIiFFEQq5FEThFFYwpoL35oKDYYpGEQm/aIkCVxLcGv70Jn40EGYPAEQ8B/6MDM4J5EEQgcBFwREBQAqREGgP+qFbCAPQERA0BAAiKEEQpABAAZnEa4xGBAAaiEAA0vCAYaDCJgQMgEW//6GRYA/Kg2/MwOkB5TcCAAX+NBMLZ4v/yAQP//ACB6vHeApHECAsBBQXlCov8CIt/DQRqCoAZC8AQEj///oVDO4IRCPgkDCAYVBKQQnBGgqpBCoYuDOII0Eh6CDv4cEl4bCFIfwCoYtE//0Aoc/IgQKBFog0BTwZABGYUvKAs/Awl//AVGAw6oBQAQbFFI2/KwQbBbohiBEQZLBHwY4CET5oMSIRoMF4kv/zcFJggoDgLEDfQaFCJYS7Cc4gtCC5O/Ggn/HQoGDWYI/Dn5dFBgL1Cl//NwQEEUYf/RoQDB/NBt4IDGghNCKIIAEGYgMDLgYADM4jBDBARSBAAToFDwbGDCARfCCIwrD34QKgEGAgdr//kCBAAxRQOACJ0/QI4ilgIiPgLSEERUBZIYiLCAIiOCAIiOCAQiNCAQiNCAfQERYQIEQ4QIEQ8B34QHEQ4QIEQ4QJEQwQJEQwQKEQoQKEQoQLEQgQLEQgQMEQYQMEQYQNEQQQNEQQQOEQLtIEQ4QPEQYQMEQYQNEQQQNEQXgCBoiBCBwA/AB0B12QCBsHSYP0BY8K/4cCCAX/+AQGj4KBRwMCfZUPBQm/CIdAepAKBE4QAB/oiFBQgWC1RGHcYJRD3/+BII3BwAQDhf//1VBQOPIIf//gzFDgV//pkDf40vDgiZELYJnFDggLEWAt/HQYcBTAayBK4ZWBSQZRFn/4FAiADCwPAH4gFDh5nCHIQcEl4oENwgcBHIbnBERM/MQgicIphoDQopoFOgIWERYoFEFwkPVxTRGJYm/Nwk/Gge/bogoBCAcB//9CoX+KIYoBQoYXC/MAt//x4oEDYQ0EAAXwFAd/PIg0CAAX9MYP+oIQBKwhvCAAWAl4FDNogABj4KCJ4IQDRQjHDBIIsBMgIXECI/kY4YABc4gAIHQTPEABIjBEJoAwgtloC3DCBLhBQokvyAQHZIIREgX/6CcIAAQMCA4LzEAAMPZgwiB/5MDAALLEd4YiBV4wOC1bNDEQXwIg35OoJGDAgQ5BAAUH//9Q4QMBNIY0FIAZKCcAQbBSQb+COAZtBAoQKBCAYpBJgl/HIUA3/0BQc/BQY0CF4Q0BK4YKBUggvEn5XEv5QCLoY6CDgooBWohXBSwYiE36jFAwZiBEQcLNwgGFESBFFDYJFJNAyRENAKLQUYbWDVxLRQDoQVBBQgXBHQZWBLoX/FogGFcQl/KApdBFwUB/50Cn4zFUYP/PYIQBKIQhBGYo0B//+rQDB4EGAYKnFIAQAI6AiFYIIAHIgp7DAAzJFLAgQOEY6NCAA5jD//6MooAGitaqoPMAH4AHqgFEgNQCBE/TArSHAAMPBQs/eowsCTYIGDg///jTJd4m///ACA0CEQsLERLkBEQl/ERBhB/oFDgf/N4oKEMIkPC4hpFOQsFXSo'))),
        46,
        atob("DhgpFSYpKyYnJCcnDg=="),
        70 | 131072
    );
}

Graphics.prototype.setFontDate = function () {
    // Actual height 26 (25 - 0)
    // 2 BPP
    return this.setFontCustom(
        E.toString(require('heatshrink').decompress(atob('AGcQAYUYgED/4ABo/wgE/AoP0v8AgNVAAMC6AsTgNUAwgmBAoYzBGAIAPDJkUDh0PAgc8gHwgghC4EP3/AAwM+3///kAgwEB/9QBYP//1QGoUOqYZBEwxIDBgMFwAMCgomCgEHEwP+oEAFgP+DIUP//QEwdQEw5SCZQoAOg2QgG4R4fAhYnCH4MAv50Bj+B+kAvsAgXwhfAgYTBnsAvgQBDAQADx4FE/ED6AbBgIZBl5jBoADBgP4gH8g/QgEL+kH/SBCl4RB/6BBgFkIwKUCACUFDgQABhYjDMAP+/rHEgPgXAKgChwDBKYM8gXggIVBgX/AYO+Ewl/FAQzBl5MEj5lBHYbODGAKhBIIf8gImCgH+eQJ6Cv4gBq4bBn+AgT3CUIMAlj3CkAhB+ihBAAUP/47El41EABkB0gFE/5VCv/gn//fgIqB7/Qvw3B+u/+jiCnoYBCAKbCh7kBTYUD/fwBgX1/sf6QMBj6bCEwIzBK4IzCSwaBCUQRHDJoP+j7rEgFwNyAdDqgGENYIFDgYwEAC1VqAECjf///5AoNvAoP/cwN//wRBt/+haMBCwXwXAkHGBkLoAFD2G/dgS4BgX//VVrb3BBAIACyBBD/wdEABWgmgFDh9LC4l9RAkC/oSEGIOAAwQFBNIcAl7gEgfeGYn0+ggEg5LPbAYTFngFEgY0EBiRbCNIaUCEzgMHAB0aUok/HYv+CQkUE6ZajBiTCGACk+AokHQAiBBCYouNsBCETYkb//gBQW//+QGIX//IQCt4KDDYP+GIcv8hrYG4IsDj////9HAX+qtv+gmBBIUP6AzBOgkDBAIQBQIKsDh4MHS4YdBgP4AoMLCAMLHwMbBIUvIAP+CwYFEgEFqhmPgJXBYpML4ASKcosDH4IABLQM/AwYZBqoACqBBOvilCIAQ6Bg4mBh/oeocCIAV/Rwkf76bDDAKoDgP8VAl/gAMBUgMf4AMBZ4NfBQIBBg//UwIMBCILdCBgKkEUZ9AgEtAoW8K4P8ZARnBj4zC8AwCCwLfCCwUPoA+Bg4WBJYZlBBQIOBBgX4gQbBTAML6F/M4OAXgW/o4bBTAPh/5jCgOkOAI5BMwYFEAAxzFYITyEAocB/wME/9PAod/wAMDn/QU4R3BPYIMCh7sCFQRlBgIMCMAIACG4QACBoMVqtVr9VJwjOFGYYAMi2vwG9GYf8hf0GYeAaQU8IoU+BgPAnrjBYgUD6A0CBgbRDBgUfBgUvAYJ3BEwP9gP8BgTBBYQUoC4P/DYIACgzILAAkG//5AoULEoLvCg/+3//M4MA/sP6EfFoMvM4vgLQIICnpIBM4fQBgxeBMYJ9Bl9Ag4IBFYP+qxnBgF+M4QFBgPgJAOALI8UAog4CAAc8AYUHBgkHVAQFCFoIMCAoKPBBgIFDVAabCngFEgfHAob2CAob2BWYk/XKDNDha1CEAODWobAB/1fKIMvoJYBWocL6CoDLgUfLQRpCBgd9BgYZB8C5BBAOWKoN+GYO//u/34bBgX/oZADSgX4MJ8VOokfFgI9BUwX+gYgC/sH+kf6D/Ch/AM4cAvhnEMIMPAYIVBngMCCoMH4AdBMYX0g4QBh/Qv0H/gzBv//AAJHC34FBJ4dq1LKRAAsPwEAMIUBGIMfSoJgCgA6CgEQB4ImPggCBjRfBgYCBn5VCv4IB/wFBRIUUKi0BDQIADn7KERoYAC/aaBa4anBAAQ6Bfgl8hZzCQIV9GQfwLgQABZQMfGgTOBQ4iYBZ4RgVoFQAwc8h5NE4A5DBnRNGADDpCSoa6BUQiVBV4a6BXgivBZIcC+DWEh9DVwm83g0E779El5nEgH9AogyEYIwFEgQ9DAAO/FQkfyBsGgMBBIM9fYP4v6mCgP/w5BBBgM/qEZDIUPH4cf7Y0E35SEDwI6EABsB3//JQQaBAAKPCv/kgwjCj4JBgIwBLYSrCUAMAtVAh+AfQN//+AnkC8Ev/f/AgM9g/QgP4j5uBbgMH4HwngaBgADBBgIpBAYU8hY9BvAMCQYMfgHwlsLKYUfgPwMAP/oSNBotVqv8lpNCEwVAgaUCngCBh/kAQKkCl4fBe4dv/5PBAAUWqieMsDzFf4gmEg//GoIABjatDHIRPCTIP+KQIFBn49BKQRZCBhL2CBgZZCvg/Dj4zEIAxNGfwRnFuB1MgEVVoIABJQKZBTYc/AwYMB6tX6tVBgJXBAILyBK4JZCBhz0BBgnghfQeYKaBoIxBn5HB//9/oOBOQWH//8BgMKyEf/xdFNhoACgr1EUIP9AoULNgK+BI4P+oFvUIW+coWADAICBgG9WQIPCLwMAnz5DBALMCM4R0BGwQMHDIZ0BgP0cgQQBh4CBgJ0Cv6aB/9ABIJYBj4jCgSaBH4LpiCQTcDAALcDAwQMIOhhKCSQSKBAAJ4CNQUPFQMHPYICCCYP+17JDv5MBPQIABt7KBOkdXOwJnDAIJ0DOwQMqTYYAMgJgDqBaHM4s9qtfOgYxDAAI+DAAIMmgWAX5wAEqrVDgJZB6AGC34GBEYU/8kGNoMAhfgGAP4DAICBBIIaBl4cCnxNBCQITBQIQMCj4MBCoNQgIMDLQIMCBAPwAYUfoAMBvocB/oMBj54Bg/4h9vPgQJB/4PBAAMsh/+PqZtCbhYMFW4gADW4IADBlcVqt9qtVJp4AKgIdBAANQOhozBAASXQgS1DAAMv/A2Et7tBVghEFawQACdYIMKDIJaDr4mBLQYzBLQbwCLQVUK5yBVr/1QIcCNgkAPIs/8BkE/55Dg/03+AHQX9gLODv9AgYhCj4XBhZnC+gJCIAM8VIYMBGAdwNxrcFM4x0FQIjCLgAMsgrPhn/lOgasBTgQgC3/5FAl/awsv/1AAwcf/4GEhbQDAAMbLQgaBE5A0BbYIFCIIkG//gAoRaByAdDn/rM5Z0ER0PVRwcA3+AEAh4FgQ3Fg5yEAwKbFh50DTYS3ERwJ2DR4XQgEq1QABOjajC1RVDZoP/MYUHD4QNCc4MG/ivCBIMHGYMHIYJVBBIIPCAYUPEYfAgBkDvgMBFIQMCPAe8H4IIBDod+TwQdBgQTC34PC/MB34WCl5TBRwd//6bEirhBABz2DqgsBTYYtBAoZnCCIP1qpeBPoMPbQYCBBAIDDBhRKBj4MDwECBge9OwbjB/xsDC4JmFl6WDAB0a1IZE//+Ewn//ozC/MAjZBCBIUfHYLlCgF9CQIPCAYU+EYYIBfgWBBgM9NQQMCYoX/BgMvNQcAgJfCh4MBhYTBgX/EgM/8kG/6DC35UBwGgDQIFBGwTXCJ4QAMgLpDfwM/cYZDBAoZaCqtX6tVBgJ9BnggCAYIICBhxKBv5HCRwML/4GBgTaBXgcP8u/hYGCv5mBhasC36CBTYIAEiDxQgrFDGgO+AoMH//ghayC/1/dIbCBBQJRBZ4ML4ECbgYBBdIbeCBgYbBdIcB+AZCl9Ah+AEwIzBgG9h6FBg/0WIJACjYTBPQQACipkIigFEVga1EBi7pBAAT2Hn4GDBgL6BAANQGbQMFgL5BACEVHAZNEbwJNEKYMBJgW/wAdE3pEFaIIADaIJEEEAIADbgIMKDIsHbgISD/ibFNYJNDCQMC1QAByBtHgSBFn5dEEwIwEgx5DG4X//IbE3/+KQpACAAUbbgJaEM4kHBgkf/49Dt/+D4UB3/9IAn4JoilEn5rEgbpMZYsP8gGE/44DHIQuFL4J1EBwQkEja8BBonADQhWCDASkCMII0Dh//IIiYFBgJoEt4/FEAIVFBwIiEBwJADAwJNECYIMCIIoKBVIYrBHQcPdwqUFABkgdQbCBGoUCewM/GwT2BgL5Cv6hBgbuBn6OCg/4j68DQQP0FwcfKYYhCOQhbBY4d/wIvCFQUCF4IeBFQMHQ4MDFQUPJoM8F4ZWBFIcwOhs0AokDEQIADn5eDAAO/NYRTDKQZgCcIkC/9VqoGE/4qDv4GBFxEvRpULfIiuCAAc+LQo+EABqODl7pETYsHJoIMCWoIMDgP+h4MD39ABgc/4AMDZQQMChZnBBgXHM4QMBnxhCBgSEDBgM/U4QMCWgbGFAB0PVgIAC+AFE/8PYwIAC+AoEh41BAAY0GgoGF3+QAoaRB/L8E3/+Xwkv//kAwcG/4OFt//OQQkCdogkBBggAILRn1NodfQJgoIkAFEl4FFGokvcQI7DAokAAooMGDIomGgEfIAsQdBwcFPIoM/AB8KAwu9AokHFAsHFCcGgP/oAFBgXwn/9BgV/hfX8AFBhfA+ixD+hYBG4UPgPwMAfwjwHBBgVB8E9Kod9r+QAoMD/4ABBgULAoJeFABEVqoACDwgZCn4GDCgUfyFvM4UH4EAIAf0gBNEXYoJCBgYdBOge8G4KBCgf5g38GYY5BGYUAl//wBWEBYZjIBggZFEwsD/EBGYZAFJoxaGM4p0FbgMAnwMCn9Aj4IBCAP0gQVBfoVAjBaQW4PQLRP0gP9LTm0LQkDKIM8dI72FgYFDDIQAHgtQAocL/5GCgEHDIJhD/s8v7IDHYP4IAXQnkHSoU8BgJHCAgRQCgE9AgN8UIXwnkPdQUP8/DV4c//jCDgF/4SpEAAhkFRYZlC+tVqpoBMoKBDgSBFn1PDAZKBEwhKBAocBoA9JexkYewlCUYMD/D2Bl4VBewYDBewacCewacBewacCRYL2BTgIVCnsLAYL2CowQBh5uC/wdBOoavBgqHBqpjMF4IRCTYRlBTYcDTYqjBaYYABcwTCDSorPGBgv4AokLawShEGYcA35ACLRuQLQqBDLQPwLQkZERoACgfBEwdV/gmE/9DEwf/8AmRVCoVBRIs/Tgv8KAgYF/kv6AGCv4BBeoIYB4EA/zCEQoIFBhi4CKQsQMJsFMAkALQb/BRog2BAAd8U4oMFiiWOGgYGCRwrpEAAMeoAZDg54CAARKBTQgtFBgyZDTYQzEgIzFl+VPYcHMgozTDIozFgQzFg2q1WgR0UuRxYWCLRIMGDIu+fokDGYsLIAgAHipBEl//FAcfDIINCgf4gP8BgW8BAPgIAQQBj5NFOgZdFWoMBBgULWoM+BgU/oEfXwTpCZYZhBHIYNBqi6OAAK7CqoVBWof/FwIFDFAMB+kGGYd8GoJACK4RnQBIJnMt5nJgX//BnQBgqBB/oLDEwqbC6BAIWopaIM4jcFQIsB/KOETYqoGYR9QGYQYCEwpACgXkDIm4AohXDLQoMJAB0ITYiKCTYX8h6bD6/Qn6bDlybEAgKbEAgKbE+ibD3ohB8DVC+AuBBgULHYKxBIQYFEOiELSgX4AwO/AwQzBgNfVwNvdJIpIiCSOgtVqgGDGQP+Job7DAAcbOgQACl4FETYZqIBg09AYRgBr6ICGYTRBIAf/DIoADbIQwD8gGESYYAC3/9Awlv/y8EjYzDAAMHXAwFDj7cEv6HDFgP5IAn0EgiLFABkOIghaBDQg+BFokB35aFI4LCFLQgTBAgUGEAioByARDEgoMGQwJiEHQQzKTYgSBRwY5FM4LJEh+AQpwgCmgCBlgCBgaHBj/AAwM/6ELJwd/wf8eBMBRot/CQkv64fDj/gh5nCgYKBl4zCngCBvglCCwRdIgQGFn5/DEwKoDFwMH//QP4IaCRIMDHYScB/ZcEt6jDV4QFDt7CE36vDOYLVEn61EgY4BACFQAQhPCn4MCJ4MfKQQMBhapD+ED/oMDgP+DgQMB39ABgd/4AMD/7jBBgZZBBgbNCBgUFAQMKLaE+AokHDwSIDTIUf///36QBY4P/4QCB6G9Cwd/h6wDIIIjEJwYAWh4wBABIsEDJAFE+DmEh8L8tUgEVq/wn///oCCgBrB/f//x2DDghrBAokDXgIAWgP4EwuAJQnQK4pjFUgkA3hAFCYwmEgF8CYvAIAn8Bgm/FokLyBYIitVAAdWAolVqASEqoFEgoMHKYJABBgXA5gMF//ADJQMEDIIgBBgYgBDJBAEspTEqJaFNwwA=='))),
        32,
        atob("BwYLERAXEQYJBwwPBgwHChAKDxAQDw8ODxAHBg8QEA0ZEhETEg8PExIGDhEPFhIUEBQRERESEhoSEhAICgcMDQcNEA4ODgoPDgYGDwgWDg8QDgoOCQ4OFQ4ODgoGChAR"),
        26 | 131072
    );
}

let lightWallpaper = require("heatshrink").decompress(atob("2Gw4n//2V3uF7uNzuFj2ezt972N/M73uNvt9nVE6c9u9N2tF2lF3EzzOZzndACHuABnr3YAyK6hZ/K7IAB7xaNK/5Z/K5PMAAPNLS5ZN9ZXvLP5XZAARXVOIPeLRpXnypXHLKnJD4IEBLOeZzhXJAAPNKx3cZwOZCYhZN9ZXvLJ/VK4WdBQpZuzNcK5oACK5XZK4WcBg/eLRqvtLJvJV5JZuzJWSAAXNK6gACLJvrK7FVK6pZGrJXCMQxZuK7AACIYJWCK6AAB7xaNK+AABK6pZjrhXfypHD7mVXgQANLJvrK9nFK4WcV4dZWyZZcK6nFrKfBAAfJK4YHC7gHCzpXQAAPeLRpXLGwYAQTwRvEK44HEK6RZaf6hOGJ4hgDK7IACLJvrK7XFIwWVW42ZW5PNLNZHEqtVK5oPBrJXEJwRXEL4a3D5hZX7xaNK4xGBqo1EK5RpFK5YbGLM7lDmc1K6IQEJwS3MAAnNLS5YMIwczAAM8K5auDK4ZfBVAOcL5ZZqEwXDK4+VWwxXJA4xXOAANZzhbW7xXKyZXCHwfJmpGBK6nJK4S3EAA4QCrizXLIwlCqZXG4pfHK45fIrJXOM4qyWAAJXKGwa3HUwa5EAwwQDfAJXOyoHDLLQdCJwUzEoZXNKIJeHW5BXQAARZXewROCmoiDW4Y+D4YGBLIpXLIglZLovJK5RZXTwRXHW45fDCIJXSZAJYF4pXCzi+K5pXUTwUznKFDW5ZZHI4ZOBL5JXEV4ZXLLKYTByZXGW5gAFK6IHErJXCMAgALK6GRiJPFK463DABBXLL5JYCK6BZOBwNRiIABibWCfwZXQdwZXRA4wAQ5pXK5JWCAAMZzmVI4/DK5YtDqZHDT4QGGK5QOFLKjRBK4gADI4c5W4oAHX4YQDmpIBrJNDJAi3IrI8BWiRXQAAMTIINVKxZXFBIpWEK5q/HW55XEypXKLIgALXwXM5IMHK5YHLBAK3Q5pXByJXMAARXLng1DBxKmIW5pWBzOcLBwTBK6C0LK50zmpXPV4gGBK6VRK6JZJnIhCyZXTU4a3QK5hWTAAZHIqZXPmZHDUAPJW6BXkWgo+B4pWKK4nJA4ZJByq2EK+ZZEqpWLK4hoGKwj+EMIZXQypXbAARWMAAIxCyYLHK463HABmRsxYeWgYAJrPM5K+LK5BWP5mWswABsJZqqtTMxc5K7hZFLrhMLABU8IIXFK6k2K4gACWby0MABFcK4czmpXSKw60GLNxXD4a3GK7BZhiJXPzhBCyZfGK7QACLNpBDqZXkWkMTKxM1K463DK75ZhWhBXEW45XhAARZlnJAC5JfHK8i0hiZPCnhAC4pXuLMK0BrhAC4a3GK9IACLD2cIAWTW4xXsWjxXHW4ZXuLLcTIAdRiJXBL4ZXwAARXWipADW4/MytZK+C0WjI/C5IIDKwi2NHA8ZqJZxiuZJIJXDW4lRK4M5K6NpzOZyy0gLCA0BzORW5U1K6IhCypXgWiE5GoNRK5S3EK6GZK8RZPrJWDK4nFA4xXNsJXoAASzNLoY7BzmRK6lpK9ZZQHgZX/AA1hK59RA4VcK6mTK9a0LiZXDmJfEK585DIWWK9xZIjJXDW4+cK5gRDK+IABsJXQLI5X9WghXDypWCipXFAARXCgxXIixX1AANZHgWRW45ZHgEALIVjBQZW3SghXPzJXBAAVpK/+ZyxXUhIICypW3sJGDqwHBiJWLV5OWK+9lIwcWW4wAHypXErIJCyAGBK+qUDzIIDK5eRK4gJDK4RZ1K49jK6swBIkAgxX0yZfHysRfYZXGgwJDsBXFWmJPDyxXHi1msJXEqJIDgoJDBAcDEAJZxK5eVA4SwEsxGDhJXHAwUQWYsGLFRGDAAUZfwa3HK5GRA4UBA4WQK4q0rJAKuDK4i3JIIYREL4wHDVoOZmBZsLwxXFnK3EfwynEW44QDWYsGK9VhfwYACJoZfBK45PDW48FM4wAELFI+BVwZXJeoIADsC3NK5BZrAAhFDqxXDgZXEVANpK44IDK5R5CK1VjIoYGBTwwAIiAQCnJXPWladEK6JDDW45Z0K5IJEK58wK6AABgxXnyZXEzRXOgwHDsBXSWkk5HgWWK4uq1WpKw+WB4UJW45Z0IohXHLJGQK8DPCK8sBKwYADK5eRK7S0csJFDixXDhJXHWgZXDjJfGLOllK4YHCK5gABsAyCW44AegxXUtJXGolAhRWK1IwDK8y0VK4eVK4dEnRXPAoIaBW4ZZ0jJXCyxXEzRXK0YqCgZfHAEsGK5rsDK4lJKxWq0AoChJXtLJxXHzKuL1WQK+YACK5s2A4RVLK4tqA4WmQ4mRWmRXDA4ZXNylAEILADL4YICyyzrLIs5K6tEolAK48JAwOpK9YACJ4VpKwOWK6oHDmAkCnQHGAFi0BtORW4hXN1JXBUwQABEQa3HLOBXS1WZjJeGoBX3AARXSWxFEowIDsBX0WgZXU0JXCpIIDK2wACK6mgK4y3BoBX/ABmUK4VKA4WjA4VEK/5XOtS3GLOxXUwhMCzRfGAAlAK/4AFJQZXMWmJWT1KhDBAc0K5RZuK69BBAcEK5hsCK/ugIQVJL4wAPK/ekH4VKK6xZnK6eUHoUKA4WoK6gABoBX2mg7CnS3GACxX0gg4CzS3GUhRZsK6Y2DA4ZXMNAOQWZxpBK9upGYYIDshEKpIXFABxXs0ZGFW4oAHhS/PoGBghZbK6WkK4yfEoEzHwlEzRXPjS/HoBXrpRXHJ4I+FK59IB4U0Bg5XlHweKA4WgW4w+EDAZHIDAyADLK5XWTwa3HA4aeD1UEK5QYDPAYAIoBXNu5XRI4ZfHhQPGTweqIxcaV5pZQu4ABvRXO1JGGW54XCABIYDEAYANK5gACLB05AwjmDW5ehIJYYHABFGmy0MK4q0Re4q3InT2HpGWHwoYDwhWKoDAByAJGK5hZT0cjdoeqgj2KpAGBHwlDO4oAJaAWpBAmJzIgBK5gACWaQ+GW44+HZAZHFAAzQDihwFC4dAK5i0TEwoIDmi3GkgHCpRXPaA54CFAhXOWiWjTwwuEA44+D0RXLaA63DA4ZXRLJ+gK44uCW4juDTwekKxVGDAcEW5RXTAAN6K5Q+Dewa4DA4j2LAA54EDBZXVWhYlDxQJEzEJAwj2LK5epA4TQEwhXbWhE0QowAHHwdIew9JzOQK4jIDDAdDPA5XaLIxXDKxWq1D2LLwzQE0a3L+5YcAALuEbogAH0ieKIwYfCaAoQDDA9B///LL6GCFoYAII4YQDTwYHD0C3GXIhfD0xwDK4IACK7l6yUDKxZXEnS3GhQHC1D2DDIgJBX4bQFK4i0hK5SVCSwg+DL4avDoZ4LOAhXGWj62CGw72HW4ZfHU4hXLzRXJLMC0F1L2HwhfKpRXLEIeqK5YAB+60hGoaeEL45XDhRXLCIUJK5y0hvWgK5VDK4+aK5mqzICBK6C0f0j2GW5AQDK5wACK6RZdIwcqHAWiL42q0IHBpBWQK6oACK7FxJ4WXAwKmEhRCEylEnRXpWjF6glEoenA4RNBAAJPSK8K0X1ODVwRXFzRX2LKwAEWwIABW4JX3AAP3Kyt6KwVABAhX2Wi15K4VJMQxX3WidzK5IACK+5ZRuhXCpQPKWh5XnAARXM0hXCg5qNK+60MuBXCy7DOLJZXsWhV5K4WnK54ABvRX3LJGUolJKyK0JK+IAB+6ZEzKuSWhJXzWhJZZK+y0GADJX4LLxX6AARX/WmJX/Wi4"))
let darkWallpaper = require("heatshrink").decompress(atob("2Gw4n/kHCgHKwHS4Ha8tY4PJ81IoHK80ggHj81A8tg8Hi8to8HJsHKu93uFEAAtmABtq1QASxAAoK4N9K4xZQLCZZoK4MLK5BZk1BXo2hYKoxZ/K5Pb3e7LLVqLOxXELP5XTuBWDAARYKohVK7u2LKxXgV4hZX6AfBWbBXdvvd7pZZtcHu936wJELCZZbK4YABLA5ZPsBWBu8GXQxZtu8NK4ZZJ2hYKoxXEvZXGLKuoK7xZV25XCuhXILNd3Kw4AB7ZZR65XCgxXKs1qLM5XKLKUHK4XWK5ZZWK6NwK5ZZKK5PUohYNLMpXOLJtNKwVwL4ZZxvpXPAAJYHLIJXIpsA7ZZNLCZZMhpXRLIS1G2BXCvpXDg5eB6izOLCeoK73Qg9wLAhXHW4cEolGLNddK6aeBu8NK4fXJ4ULK4VAA4V7A4RZOtRZaKyfdUwfdWIRXE3e0oi3HLNRWT6BGCuAHC7a3Cu5eCW5AADLBpZVK4xHBIoZXR7pXHA4cEK4xZCshZiHw0NK5aeDvoIDL4ZWCK4nUK5CzQLCY9C6o1CK7PdKwO9A4S3CLBRZhewxGEAA6eDNAYYHK4a3D2hYKo1kLLqeLqC2GK54HDK4ZZIpsAhpZCWbg2Cq5GG6r1DfwwQEOAZfIK4hZGCAUEWYZYNtRXWHwddK46nDW47QE7ZYGLIYYCvq4ELLI+GJ4aeLXIgYDM4YYG7ZaHpofDK4gABLBpZJTww+DW5YABgHdgBeGW5BZBK4u9K5RZXFgPVHxa3HAA4YIA4ZpBhpZE2BXMLKBXKuo1DW5ZXMDA7ICWwJXCaAd93ZYKoxZRewpXDW5gAHvpOFDBAPD3bQDK4O72hZbTwpXYT4JXKEBcLW4RZbK5K3HewhXlLLSeGrpfFGwa3DABAXC7r2Du5fOu/bK4oABLBVEK5g/EVANVA4g+GABCeHXAYHDvq3JLIO9gENLLCeNHw4AHexAABgEAAoZXDW5DICWwpZSK513gpWLYwT2GO5RXEW46wE3vQhpZQexoAPHwZ4MK4amCW5F9K4YIBuHb2hYKoxXDq5XfPBj+GK5IGBVwLiCW4RZNK9twK4ZGCDAhfH7q3HLJdVK8A+DK6AIDA4cNPA1wK4ZZLqodDADF1HwwPL7twBIZQCAwxXEV4gADK5BWbAANd7vVM54QFuEAN4hXDaAbYB7ZZNK7w+GBxCeGABC/DEIZfDLA5ZEK7wAPTwxnLK5BZJ2hXBq5XtH4PVYBZXIKwhZLK9FwAwsAKxd3vpLDL45ZMV9wAOK4fQK5vd7ZXEPxgAwhpXSLIpAmPyxXD663GLJqu8u5DDK4ZfDABpX/AALKDK/4AOuBXHrpX/ABt1II5WQK/t9IAXVW45X/ABUNIAXQK/5XaW4ZX/ABddIAXXK/4ASIAdXW4xX/uAKKIAcHW4xX/ABV1IA5JEqBdMK//VW4/QWxojHlnCK/0HA4N9K6N5zOZy5YxUwpfEJAYHEK5pWBzOTK+MNUwinEW4ZXVzJXxuFVqBeGW5JXMuRX1AA1dI4XXW4xXNvJX/7tXW4xX/ABZHDK7OTK29wI4cHW4xXNnJXCy5X3upHHKxRXGKwRX96q3HK/4AKvpXGW4hXRk5X3rpGC6BXUuZXDK25XEq63GK5t5K/5XEhpXUzhW3uFVqpXFL4YAH6sXDQcpK4WSK+91K4IABg5XPiMRLIXJK4WXK/gIDK5fQK4IABu5WCK/4ABuBWK7tXK4cXK4c3K/4HBWAVVgFVK5MSK4ZW3K4lXL48HWwJdCAAMHK4ccK49zzOSK/wHCK4fVu5XDjJXDAwISBAwUnLGKmEAAMFA4VQL4ZXMyYHCiYHCy6wzVwZXEW4pXHnJPDL42SEQdyzM3L2ZXFL4fQK4nJJ4WRW44iDA4RX1A4YGCL4VVqJPBIwSnBK4UpW4cXDIN8A4ZYxVAKuDK44ABqJXDzNxiMXAwa3Ci95K+oAGK5FTK4iwBVwZXDW4ooJuJWsupXDg5XDrJXEAA0hK4XJV/ZXEWohXMKwURA4ZX/AgT/EK58xiMXK+sFK5E5KxWcKwUSBAdxBARX0KwdXAwiuLyROCji3HLOhXVyJMCjJXJiMXK/NSK5eVqpXFyZXGWWFwK4cHK4dTK5c1CoUpW4xZ0upXDWwlZK5cVCoXJK50Ri5X/AAIVDA4fBK5ZZrK5L2DAA+cCgVRBAclK5oABK85WDqAHEewYAHyQVCqS3FqJZ1K4dXA4dTKxWZyoVCrhXFLKMXK9ciVxZXErIHCyYeDAAKyyK45VLAAPFCoUZA4WRDwdSmUVLK8HK7gdDK5slCoU5W41RAwOSAoRYOi6viA4ZXNmoVC5K3GrIHCEoayPLLt1GANQK6JPDW48pA4xZRLDkFVwhXOyZEBrgHDJoa3HAAVRLNhXSzPCkYGEJgYHDmpXFLKMXK9wAFzhXHipXHAAKyuK6mSI4VSW45Z1K6mVIoVcW44AJqJYOi5Xv4pECrK3GLOxXUmpXGW4YAOLB0RK6/MK6ZADnJXVWSBZW5gABK6vJA4XFK6RZRi5FBg5XT5hCDABecHoYIDkpXUAAKyiK4ZZPyRXHKyxZjK4pZNyo4Cqa3HAC1RLB0XK508LA/MK5PFG4VcA4WTK7RZfmczLKM1GoVZW4wAbLB0RK5oABLBBZGGYZXjWSBZKK4ZZK5JXHnIHC4pXfLKMXK5pZMzgwDMAclIJZoBMyqyPLIxXHmc8LJGSFwa3HAA9TBwJvELMRXNLJKXEKwRHMrK/PqsiBJFRWSFxK5YABK5KeCzOTIpcpCAU1CBofKLKJXMLIo+DrnJIwOVHwuSHIgPCK5lSX5xYOiMiLBxZCFwdcAwPJK4Y+DG4gHCI5lcB4R4EWS0ikUjLB08HwcsW44+C4pXHIxdZK55ZOK4JZQJ4c8K4RfDHw63DzhELlJXRAAJXOLJ0yIwRWCK4ivHA4eSIRc5K6ZZKK4oABWBoDBK4S3F5OZA4b2QCwIABDAYAIqMhAwpXOLJoAD5nCEwS3DFwZXJYoYACB4WZKxgOByIJGK5xZQniPBlhXHlKeHU4PFAwdSK554DBAkszMxK58ikZZPKwfDew6pDHwWcB4dTB4QIEAA54DEAZwDitVK5xZU4Q2DAwKOFHwYHDrgHCyRXLPAbQDW4ZfCqJXOAAJYOmfMe4i3C5IHDnJXGHweVK5YPCV4h4DGIZXQLKCFDqRXC5g2DHwa3HK6C3HDAf/LCRZNJwdTK4aGCqY1Czi3HOAYAHqRXHA4avD/4ABLCUjK5QtDrhXDWAU85g1ByaWHOAYAHrhwHK4YYDu9/LAPyLLgtDqczKIIAHyT2LqRsCAAdZB4QYDW5F3AAJZFl5ZXEoYLDK47lDHwaeEW4RXMW5BXCAAJYB/6ySkRXJBIpXJqaeKB4dVnIICya3LK4hZcmolCXQxZEfAdcU4WVTwwHDW4a5EL4YQDqZXGLK8jWAgFDAAs8K4JGDrgGBU4ieDK4hWDBITHDCAlZK5F3v5YB+RZWABc8IwcsW4THCK52ZzheGK5hZnIwa2C5klA4UpIwS3DU4gAHK4cpK5YABLAP/LCUiKxcyK4ZWC5gHDnJGCW4dcK5eTX4ZXNLMRGDqszKwPDL4vJzK3DrJXLCIRnBK55ZXkZXLqQGBnnCW45XRzPMAQJXRu9/LAPyLLJXDqZfHK4YIDnJXNAARXSLLpXLqZXD4oICKyBXVAAJYBLKhXT5gHBrnM5JXmLIhYSLIMyJ4S3DkpfFK4XDnhdDLJxXYLLBQBVwczKwVVkYHCKggAELJhXau9/LAPyLCRNDK5JZLK8xZbmRXDKwhZVK7pZYmc1K5fDmZYI5JXmAAJYB/5YSkpXLAAZZOK8JZVK4dSK5cznhZMK8d3v5ZRK6JZLK8xZE+RXRkUjLLBXmLKBXDA4ZZPK+AABLAP/LBRXGAAJYOLIxXqLJshKwxZWK9izPAA8jLB08K+F3v5YB+RZjK95ZnK+IABLAP/LCUiK/5ZkK+pZXkZXIA=="))
let lockIcon = atob("HBzEAv//AAD//4IQQQgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIiIiIiERERERIiIiIiIiIiIiERERERERIiIiIiIiIiERAAAAABESIiIiIiIiERAAAAAAAREiIiIiIiERAAAAAAAAERIiIiIiERAAAREREAABESIiIiERAAARERERAAAxEiIiIRAAARESIREQAAESIiIhEAARESIiEREAARIiIiEQABESIiIhEQABEiIiIRAAESIiIiIRAAESIiIhEAARIiIiIhEAARIiIiEQABEiIiIiEQABEiIRFDEBMzMzMzMzEBMRERERERERERERERERERERERAAAAAAAAAAAAAAARERAAAAAAAAAAAAAAAAEREAAAAAAAAAAAAAAAAREQAAAAAAAAAAAAAAABERAAAAAAAAAAAAAAAAEREAAAAAAAAAAAAAAAAREQAAAAAAAAAAAAAAABERAAAAAAAAAAAAAAAAEREAAAAAAAAAAAAAAAAREQAAAAAAAAAAAAAAABEREAAAAAAAAAAAAAABERERERERERERERERERERERERERERERERERERERE=")

function drawTextWithOutlineThickness(text, x, y, textColor, outlineColor, thickness) {
    g.setColor(outlineColor);
    for (let dx = -thickness; dx <= thickness; dx++) {
        for (let dy = -thickness; dy <= thickness; dy++) {
            if (Math.abs(dx) + Math.abs(dy) <= thickness) {
                g.drawString(text, x + dx, y + dy);
            }
        }
    }
    g.setColor(textColor);
    g.drawString(text, x, y);
}



// Drawing the watch face
function drawWatchFace() {
    // Detect if we're in dark mode
    let isDarkMode = g.theme.bg < 0x7FFF;

    // Dark mode colors for text
    let textColor = isDarkMode ? 0xFFFF : 0x0000;
    let outlineColor = isDarkMode ? 0x0000 : 0xFFFFFF;

    let date = new Date();
    let hours = date.getHours();
    let minutes = date.getMinutes();

    // Screen size
    let screenWidth = g.getWidth();
    let screenHeight = g.getHeight();
    let centerX = screenWidth / 2;

    // Clear background and draw wallpaper
    g.clear();
    g.drawImage(isDarkMode ? darkWallpaper : lightWallpaper, 0, 0);

    // Format time and date
    let timeStr = ("0" + hours).slice(-2) + ":" + ("0" + minutes).slice(-2);
    let months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun",
        "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
    let dateStr = `${months[date.getMonth()]} ${date.getDate()}, ${date.getFullYear()}`;

    // Estimate sizes
    g.setFontClock();
    let timeWidth = g.stringWidth(timeStr);
    let timeHeight = 58;
    let spacing = 10;
    let dateHeight = 22;

    let totalHeight = timeHeight + spacing + dateHeight;
    let startY = Math.floor((screenHeight - totalHeight) / 2);

    // Draw time with bold outline
    drawTextWithOutlineThickness(
        timeStr,
        centerX - (timeWidth / 2),
        startY,
        textColor,
        outlineColor,
        5
    );

    // Draw date with thinner outline
    g.setFontDate();
    let dateWidth = g.stringWidth(dateStr);
    drawTextWithOutlineThickness(
        dateStr,
        centerX - (dateWidth / 2),
        startY + timeHeight + spacing,
        textColor,
        outlineColor,
        3
    );

    // Draw appropriate lock icon based on theme
    function drawLockIcon() {
        g.reset();
        g.drawImage(
            lockIcon,
            6, 4
        );
    }

    // If screen locked and setting enabled, draw lock icon
    if (Bangle.isLocked()) {
        drawLockIcon();
    }
}

// Mark this app as a clock so launcher button works
Bangle.setUI({
    mode: 'clock',
    remove: function () {
        require('widget_utils').show();
    }
});

// Redraw on lcdPower and lock events
Bangle.on('lcdPower', on => {
    if (on) drawWatchFace();
});

Bangle.on('lock', drawWatchFace);


// Redraw every minute
setInterval(drawWatchFace, 60000);
drawWatchFace();

Bangle.loadWidgets();
require("widget_utils").swipeOn();