// Custom Cantarell Bold font
Graphics.prototype.setFontCantarellBold = function () {
    return this.setFontCustom(
        atob('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/8AAAAAAAAAAAAAP/8AAAAAAAAAAAAAP/8AAAAAAAAAAAAAP/8AAAAAAAAAAAAAP/8AAAAAAAAAAAAAP/8AAAAAAAAAAAAAP/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHwAAAAAAAAAAAAAL/wAAAAAAAAAAAAL//wAAAAAAAAAAAL///wAAAAAAAAAAb////wAAAAAAAAAb/////wAAAAAAAAb/////9AAAAAAAAb/////9AAAAAAAAb/////5AAAAAAAAf/////5AAAAAAAAf/////5AAAAAAAAf/////5AAAAAAAAD/////5AAAAAAAAAD////5AAAAAAAAAAD///4AAAAAAAAAAAD//4AAAAAAAAAAAAD/0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAG///5AAAAAAAAAAH/////4AAAAAAAAA///////gAAAAAAAH///////8AAAAAAAf////////QAAAAAA/////////wAAAAAD//+QABf//8AAAAAH//gAAAA//9AAAAAP/9AAAAAH//AAAAAf/0AAAAAB//QAAAAv/wAAAAAA//gAAAA//QAAAAAAf/wAAAA//AAAAAAAP/wAAAA//AAAAAAAL/wAAAA//AAAAAAAL/wAAAA//AAAAAAAL/wAAAA//AAAAAAAP/wAAAA//QAAAAAAf/wAAAAv/wAAAAAA//gAAAAP/4AAAAAC//AAAAAP/+AAAAAL//AAAAAH//0AAAB//9AAAAAC///kABv//4AAAAAA/////////wAAAAAAP////////AAAAAAAD///////8AAAAAAAAv//////QAAAAAAAAC/////0AAAAAAAAAAFv//kAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUAAAAAAAAAAAAAAA/QAAAAAAFVQAAAAB/9AAAAAAL/wAAAAC/9AAAAAAL/wAAAAD/8AAAAAAL/wAAAAH/4AAAAAAL/wAAAAP/0AAAAAAL/wAAAAP/wAAAAAAL/wAAAAv/gAAAAAAL/wAAAA//QAAAAAAL/wAAAA///////////wAAAA///////////wAAAA///////////wAAAA///////////wAAAA///////////wAAAA///////////wAAAA///////////wAAAAAAAAAAAAAL/wAAAAAAAAAAAAAL/wAAAAAAAAAAAAAL/wAAAAAAAAAAAAAL/wAAAAAAAAAAAAAL/wAAAAAAAAAAAAAL/wAAAAAAAAAAAAAL/wAAAAAAAAAAAAAL/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC9AAAAAAAAFQAAAAD/4AAAAAAH/wAAAAH/0AAAAAB//wAAAAP/wAAAAAL//wAAAAP/wAAAAB///wAAAAf/gAAAAH///wAAAAv/QAAAAv///wAAAAv/AAAAB////wAAAA//AAAAH////wAAAA/+AAAAf/+L/wAAAA/+AAAA//0L/wAAAA/+AAAD//QL/wAAAA/+AAAL/9AL/wAAAA/+AAAf/0AL/wAAAA//AAA//gAL/wAAAA//AAC//AAL/wAAAAv/gAH/8AAL/wAAAAL/0Af/0AAL/wAAAAP/9B//gAAL/wAAAAH/////AAAL/wAAAAC////0AAAL/wAAAAA////QAAAL/wAAAAAP//9AAAAL/wAAAAAC//gAAAAL/wAAAAAABQAAAAAL/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAB0AAAAAAAG/QAAAAD/kAAAAAAP/gAAAAH/8AAAAAAP/wAAAAL/0AAAAAAP/0AAAAP/wAAAAAAL/4AAAAf/gAAAAAAH/4AAAAv/QABVQAAD/8AAAAv/AAL/wAAD/8AAAA//AAL/wAAD/8AAAA//AAL/wAAD/8AAAA//AAP/0AAD/8AAAA//AAP/0AAD/8AAAA//AAP/4AAD/8AAAA//QAv/8AAH/4AAAAv/gA//8AAP/0AAAAf/0D//+AAf/wAAAAP//////QA//wAAAAL//////4H//QAAAAD//////////AAAAAC////f////9AAAAAAv//9L////0AAAAAAH//wD////QAAAAAAAakAAv//9AAAAAAAAAAAAG//QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAL/AAAAAAAAAAAAAB//AAAAAAAAAAAAAL//AAAAAAAAAAAAB///AAAAAAAAAAAAL///AAAAAAAAAAAB////AAAAAAAAAAAP////AAAAAAAAAAC/////AAAAAAAAAAf//9v/AAAAAAAAAC///gv/AAAAAAAAAf//8Av/AAAAAAAAC///QAv/AAAAAAAAf//4AAv/AAAAAAAD///QAAv/AAAAAAAf//4AAAv/AAAAAAA///QAAAv/AAAAAAA//+qqqq//AAAAAAA///////////wAAAA///////////wAAAA///////////wAAAA///////////wAAAA///////////wAAAA///////////wAAAAAAAAAAAv/AAAAAAAAAAAAAAv/AAAAAAAAAAAAAAv/AAAAAAAAAAAAAAv/AAAAAAAAAAAAAAv/AAAAAAAAAAAAAAv/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFAAAAAAAAAAAAAAb/QAAAA/////9AAAv/QAAAA/////9AAAf/gAAAA/////8AAAP/gAAAA/////8AAAP/wAAAA/////8AAAP/wAAAA/////8AAAP/wAAAA/+VX/8AAAP/wAAAA/+AD/4AAAP/wAAAA/+AD/4AAAL/wAAAA/+AD/4AAAP/wAAAA/+AD/8AAAP/wAAAA/+AD/8AAAP/wAAAA/+AD/8AAAP/wAAAA/+AD/8AAAf/wAAAA/+AD/+AAAv/gAAAA/+AC//AAA//QAAAA/+AB//QAB//AAAAA/+AA//0AH//AAAAA/+AAv/+Av/9AAAAA/+AAf/////8AAAAA/+AAL/////0AAAAA/+AAD/////QAAAAA/+AAA////9AAAAAA/+AAAL///0AAAAAAAAAAABv/9AAAAAAAAAAAAAAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABVQAAAAAAAAAAAAv///5AAAAAAAAAAf/////0AAAAAAAAH///////AAAAAAAAv///////wAAAAAAD////////8AAAAAAP/////v//9AAAAAAv////gAf//AAAAAA//3/9AAD//QAAAAD//D/4AAA//gAAAAD/8L/wAAAf/wAAAAL/0P/gAAAP/wAAAAP/wP/gAAAL/wAAAAf/gP/QAAAH/wAAAAv/QP/QAAAH/wAAAAv/AP/gAAAL/wAAAA//AP/wAAAP/wAAAA//AP/0AAAf/gAAAA/+AL/8AAA//QAAAA/+AH/+AAD//AAAAA/+AD//0Af/9AAAAA/+AC//////8AAAAA/+AA//////wAAAAA//AAP/////QAAAAAupAAD////8AAAAAAAAAAAv///gAAAAAAAAAAAC//kAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVVAAAAAAAAAAAAAA//AAAAAAAAAAAAAA//AAAAAAAAAAAAAA//AAAAAAAAAAAAAA//AAAAAAAAAQAAAA//AAAAAAAAHwAAAA//AAAAAAAAvwAAAA//AAAAAAAH/wAAAA//AAAAAAB//wAAAA//AAAAAAL//wAAAA//AAAAAB///wAAAA//AAAAAf///gAAAA//AAAC///4AAAAA//AAAAf///QAAAAA//AAAH///4AAAAAA//AAAv//+AAAAAAA//AAH///0AAAAAAA//AB///9AAAAAAAA//AL///gAAAAAAAA//B///8AAAAAAAAA//f///QAAAAAAAAA/////4AAAAAAAAAA////+AAAAAAAAAAA////0AAAAAAAAAAA///9AAAAAAAAAAAA///gAAAAAAAAAAAA//9AAAAAAAAAAAAA//QAAAAAAAAAAAAA/4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABv+QAAAAAAAAAAAAP//8AAAAAAAC/+AB////AAAAAAAf//0H////wAAAAAB///9P////4AAAAAD/////////9AAAAAL//////gf//AAAAAP/////8AD//AAAAAf/4L//wAA//QAAAAv/gC//QAAv/gAAAA//AA/+AAAP/wAAAA/+AAv9AAAP/wAAAA/+AAP8AAAL/wAAAA/9AAP8AAAL/wAAAA/+AAL9AAAL/wAAAA/+AAP+AAAL/wAAAA//AAf/AAAP/wAAAA//QA//gAAP/wAAAAv/0D//wAAv/gAAAAf/////4AB//QAAAAP//////QL//AAAAAH/////////9AAAAAD///9f////8AAAAAA///0P////0AAAAAAH//QD////QAAAAAAAWQAAv//9AAAAAAAAAAAAH//QAAAAAAAAAAAAAFQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG/+QAAAAAAAAAAAA///8AAAAAAAAAAAH////QAAGrgAAAAAf////0AAP/wAAAAB/////8AAL/wAAAAD/////+AAL/wAAAAH//QL//AAL/wAAAAP/4AC//QAL/wAAAAf/wAA//gAL/wAAAAv/QAAP/wAP/wAAAA//AAAP/wAP/wAAAA/+AAAL/wAP/gAAAA/9AAAH/wAf/gAAAA/9AAAH/wAv/QAAAA/+AAAL/wA//AAAAA//AAAL/wC/+AAAAA//AAAP/gH/9AAAAAv/wAAf/Av/8AAAAAf/4AA//H//0AAAAAP/+AH/////gAAAAAH//+//////AAAAAAD////////8AAAAAAA////////gAAAAAAAP//////9AAAAAAAAB//////gAAAAAAAAAG////kAAAAAAAAAAABVVAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//wAAAP/8AAAAAAA//wAAAP/8AAAAAAA//wAAAP/8AAAAAAA//wAAAP/8AAAAAAA//wAAAP/8AAAAAAA//wAAAP/8AAAAAAA//wAAAP/8AAAAAAAAAAAAAAAAAAA'),
        46,
        atob("CxIhHyAfISAfICAgCw=="),
        48 | 131072
    );
};

// Wallpapers
var lightWallpaper = require("heatshrink").decompress(atob("mEw4n/AAIIC/H/g/gg9fgkfxEf/FA/kfgHgx8R/Hg//xg4jDqoAEkQAEu4AEogAEC/4X/kURAAgXQkIXFi4XpcoYX53YAEzOZyIXFjGIxHMAAgX/C8WxaQoXEAAoXFBgwXKjgXdiASDABQX/C5dmAAIXRjLPBC/4XLa6AXdsIXQCwIXDAAWq1WhC4sXu93CgQX/C8UzAAmIxGBC4sd7vdkQAEC/4XRAAgXoxAXFCwIXPAAQUCC/4XoA="))
var darkWallpaper = require("heatshrink").decompress(atob("2Gw4n//2V3uF7uNzuFj2ezt972N/M73uNvt9nVE6c9u9N2tF2lF3EzzOZzndACHuABnr3YAyK6hZ/K7IAB7xaNK/5Z/K5PMAAPNLS5ZN9ZXvLP5XZAARXVOIPeLRpXnypXHLKnJD4IEBLOeZzhXJAAPNKx3cZwOZCYhZN9ZXvLJ/VK4WdBQpZuzNcK5oACK5XZK4WcBg/eLRqvtLJvJV5JZuzJWSAAXNK6gACLJvrK7FVK6pZGrJXCMQxZuK7AACIYJWCK6AAB7xaNK+AABK6pZjrhXfypHD7mVXgQANLJvrK9nFK4WcV4dZWyZZcK6nFrKfBAAfJK4YHC7gHCzpXQAAPeLRpXLGwYAQTwRvEK44HEK6RZaf6hOGJ4hgDK7IACLJvrK7XFIwWVW42ZW5PNLNZHEqtVK5oPBrJXEJwRXEL4a3D5hZX7xaNK4xGBqo1EK5RpFK5YbGLM7lDmc1K6IQEJwS3MAAnNLS5YMIwczAAM8K5auDK4ZfBVAOcL5ZZqEwXDK4+VWwxXJA4xXOAANZzhbW7xXKyZXCHwfJmpGBK6nJK4S3EAA4QCrizXLIwlCqZXG4pfHK45fIrJXOM4qyWAAJXKGwa3HUwa5EAwwQDfAJXOyoHDLLQdCJwUzEoZXNKIJeHW5BXQAARZXewROCmoiDW4Y+D4YGBLIpXLIglZLovJK5RZXTwRXHW45fDCIJXSZAJYF4pXCzi+K5pXUTwUznKFDW5ZZHI4ZOBL5JXEV4ZXLLKYTByZXGW5gAFK6IHErJXCMAgALK6GRiJPFK463DABBXLL5JYCK6BZOBwNRiIABibWCfwZXQdwZXRA4wAQ5pXK5JWCAAMZzmVI4/DK5YtDqZHDT4QGGK5QOFLKjRBK4gADI4c5W4oAHX4YQDmpIBrJNDJAi3IrI8BWiRXQAAMTIINVKxZXFBIpWEK5q/HW55XEypXKLIgALXwXM5IMHK5YHLBAK3Q5pXByJXMAARXLng1DBxKmIW5pWBzOcLBwTBK6C0LK50zmpXPV4gGBK6VRK6JZJnIhCyZXTU4a3QK5hWTAAZHIqZXPmZHDUAPJW6BXkWgo+B4pWKK4nJA4ZJByq2EK+ZZEqpWLK4hoGKwj+EMIZXQypXbAARWMAAIxCyYLHK463HABmRsxYeWgYAJrPM5K+LK5BWP5mWswABsJZqqtTMxc5K7hZFLrhMLABU8IIXFK6k2K4gACWby0MABFcK4czmpXSKw60GLNxXD4a3GK7BZhiJXPzhBCyZfGK7QACLNpBDqZXkWkMTKxM1K463DK75ZhWhBXEW45XhAARZlnJAC5JfHK8i0hiZPCnhAC4pXuLMK0BrhAC4a3GK9IACLD2cIAWTW4xXsWjxXHW4ZXuLLcTIAdRiJXBL4ZXwAARXWipADW4/MytZK+C0WjI/C5IIDKwi2NHA8ZqJZxiuZJIJXDW4lRK4M5K6NpzOZyy0gLCA0BzORW5U1K6IhCypXgWiE5GoNRK5S3EK6GZK8RZPrJWDK4nFA4xXNsJXoAASzNLoY7BzmRK6lpK9ZZQHgZX/AA1hK59RA4VcK6mTK9a0LiZXDmJfEK585DIWWK9xZIjJXDW4+cK5gRDK+IABsJXQLI5X9WghXDypWCipXFAARXCgxXIixX1AANZHgWRW45ZHgEALIVjBQZW3SghXPzJXBAAVpK/+ZyxXUhIICypW3sJGDqwHBiJWLV5OWK+9lIwcWW4wAHypXErIJCyAGBK+qUDzIIDK5eRK4gJDK4RZ1K49jK6swBIkAgxX0yZfHysRfYZXGgwJDsBXFWmJPDyxXHi1msJXEqJIDgoJDBAcDEAJZxK5eVA4SwEsxGDhJXHAwUQWYsGLFRGDAAUZfwa3HK5GRA4UBA4WQK4q0rJAKuDK4i3JIIYREL4wHDVoOZmBZsLwxXFnK3EfwynEW44QDWYsGK9VhfwYACJoZfBK45PDW48FM4wAELFI+BVwZXJeoIADsC3NK5BZrAAhFDqxXDgZXEVANpK44IDK5R5CK1VjIoYGBTwwAIiAQCnJXPWladEK6JDDW45Z0K5IJEK58wK6AABgxXnyZXEzRXOgwHDsBXSWkk5HgWWK4uq1WpKw+WB4UJW45Z0IohXHLJGQK8DPCK8sBKwYADK5eRK7S0csJFDixXDhJXHWgZXDjJfGLOllK4YHCK5gABsAyCW44AegxXUtJXGolAhRWK1IwDK8y0VK4eVK4dEnRXPAoIaBW4ZZ0jJXCyxXEzRXK0YqCgZfHAEsGK5rsDK4lJKxWq0AoChJXtLJxXHzKuL1WQK+YACK5s2A4RVLK4tqA4WmQ4mRWmRXDA4ZXNylAEILADL4YICyyzrLIs5K6tEolAK48JAwOpK9YACJ4VpKwOWK6oHDmAkCnQHGAFi0BtORW4hXN1JXBUwQABEQa3HLOBXS1WZjJeGoBX3AARXSWxFEowIDsBX0WgZXU0JXCpIIDK2wACK6mgK4y3BoBX/ABmUK4VKA4WjA4VEK/5XOtS3GLOxXUwhMCzRfGAAlAK/4AFJQZXMWmJWT1KhDBAc0K5RZuK69BBAcEK5hsCK/ugIQVJL4wAPK/ekH4VKK6xZnK6eUHoUKA4WoK6gABoBX2mg7CnS3GACxX0gg4CzS3GUhRZsK6Y2DA4ZXMNAOQWZxpBK9upGYYIDshEKpIXFABxXs0ZGFW4oAHhS/PoGBghZbK6WkK4yfEoEzHwlEzRXPjS/HoBXrpRXHJ4I+FK59IB4U0Bg5XlHweKA4WgW4w+EDAZHIDAyADLK5XWTwa3HA4aeD1UEK5QYDPAYAIoBXNu5XRI4ZfHhQPGTweqIxcaV5pZQu4ABvRXO1JGGW54XCABIYDEAYANK5gACLB05AwjmDW5ehIJYYHABFGmy0MK4q0Re4q3InT2HpGWHwoYDwhWKoDAByAJGK5hZT0cjdoeqgj2KpAGBHwlDO4oAJaAWpBAmJzIgBK5gACWaQ+GW44+HZAZHFAAzQDihwFC4dAK5i0TEwoIDmi3GkgHCpRXPaA54CFAhXOWiWjTwwuEA44+D0RXLaA63DA4ZXRLJ+gK44uCW4juDTwekKxVGDAcEW5RXTAAN6K5Q+Dewa4DA4j2LAA54EDBZXVWhYlDxQJEzEJAwj2LK5epA4TQEwhXbWhE0QowAHHwdIew9JzOQK4jIDDAdDPA5XaLIxXDKxWq1D2LLwzQE0a3L+5YcAALuEbogAH0ieKIwYfCaAoQDDA9B///LL6GCFoYAII4YQDTwYHD0C3GXIhfD0xwDK4IACK7l6yUDKxZXEnS3GhQHC1D2DDIgJBX4bQFK4i0hK5SVCSwg+DL4avDoZ4LOAhXGWj62CGw72HW4ZfHU4hXLzRXJLMC0F1L2HwhfKpRXLEIeqK5YAB+60hGoaeEL45XDhRXLCIUJK5y0hvWgK5VDK4+aK5mqzICBK6C0f0j2GW5AQDK5wACK6RZdIwcqHAWiL42q0IHBpBWQK6oACK7FxJ4WXAwKmEhRCEylEnRXpWjF6glEoenA4RNBAAJPSK8K0X1ODVwRXFzRX2LKwAEWwIABW4JX3AAP3Kyt6KwVABAhX2Wi15K4VJMQxX3WidzK5IACK+5ZRuhXCpQPKWh5XnAARXM0hXCg5qNK+60MuBXCy7DOLJZXsWhV5K4WnK54ABvRX3LJGUolJKyK0JK+IAB+6ZEzKuSWhJXzWhJZZK+y0GADJX4LLxX6AARX/WmJX/Wi4"))


// === Helper: Draw thick outline text ===
function drawTextWithOutline(text, x, y, textColor, outlineColor) {
    g.setColor(outlineColor);
    [-3, 0, 3].forEach(dx => {
        [-3, 0, 3].forEach(dy => {
            if (dx || dy) g.drawString(text, x + dx, y + dy);
        });
    });
    g.setColor(textColor);
    g.drawString(text, x, y);
}

// === Helper: Draw thin outline text (for date) ===
function drawTextWithThinOutline(text, x, y, textColor, outlineColor) {
    g.setColor(outlineColor);
    [-2, 0, 2].forEach(dx => {
        [-2, 0, 2].forEach(dy => {
            if (dx || dy) g.drawString(text, x + dx, y + dy);
        });
    });
    g.setColor(textColor);
    g.drawString(text, x, y);
}

// === Main watchface drawing ===
function drawWatchFace() {
    let date = new Date();
    let hours = date.getHours();
    let minutes = date.getMinutes();

    // Determine theme and colors
    let isDarkMode = g.theme.bg < 0x7FFF;
    let textColor = isDarkMode ? 0xFFFF : 0x0000;
    let outlineColor = isDarkMode ? 0x0000 : 0xFFFFFF;

    // Screen size
    let screenWidth = g.getWidth();
    let screenHeight = g.getHeight();
    let centerX = screenWidth / 2;

    // Clear background and draw wallpaper
    g.clear();
    g.drawImage(isDarkMode ? darkWallpaper : lightWallpaper, 0, 0);

    // Format time and date
    let timeStr = (" " + hours).substr(-2) + ":" + ("0" + minutes).substr(-2);
    let months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun",
        "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
    let dateStr = `${months[date.getMonth()]} ${date.getDate()}, ${date.getFullYear()}`;

    // Estimate sizes
    g.setFontCantarellBold();
    let timeWidth = g.stringWidth(timeStr);
    let timeHeight = 48;
    let spacing = 10;
    let dateHeight = 16;

    let totalHeight = timeHeight + spacing + dateHeight;
    let startY = Math.floor((screenHeight - totalHeight) / 2);

    // === Draw Time ===
    drawTextWithOutline(
        timeStr,
        centerX - (timeWidth / 2),
        startY,
        textColor,
        outlineColor
    );

    // === Draw Date ===
    g.setFont("6x8", 2);
    let dateWidth = g.stringWidth(dateStr);
    drawTextWithThinOutline(
        dateStr,
        centerX - (dateWidth / 2),
        startY + timeHeight + spacing,
        isDarkMode ? 0xAAAA : 0x0000,
        outlineColor
    );
}

// Mark this app as a clock so launcher button works
Bangle.setUI({
    mode: 'clock',
    remove: function () {
      require('widget_utils').show(); // safely re-show widgets
    }
  });
  

// === Auto redraw on screen wake and every minute ===
Bangle.on('lcdPower', function (on) {
    if (on) drawWatchFace();
});
setInterval(drawWatchFace, 60000);
drawWatchFace();

// === Prevent widgets from drawing over the watchface ===
Bangle.on('lcdPower', on => {
    if (on) {
        drawWatchFace();
    } else {
    }
});



Bangle.loadWidgets();
require("widget_utils").swipeOn(); // hides widgets but lets you swipe to see them


