// Load settings from Storage or use defaults
var settings = require("Storage").readJSON("settings.json", 1) || {
  showLockIconWhenLocked: true
};

const lockIcon = {
  width: 16, height: 16, bpp: 1, transparent: 0,
  buffer: E.toUint8Array(atob("DhABH+D/wwMMDDAwwMf/v//4f+H/h/8//P/z///f/g=="))
};

function drawLockIcon() {
  if (Bangle.isLocked()) {
    g.setColor(1); // white
    g.drawImage(lockIcon, 10, 5); // adjust position as needed
  }
}



// Cantarell fonts. Bold for the clock, small for the date.
Graphics.prototype.setFontCantarellBold = function () {
    // Actual height 46 (47 - 2)
    // 2 BPP
    return this.setFontCustom(
        E.toString(require('heatshrink').decompress(atob('AH4AC3//4ANKhf//gc/DkUVqtASLUB34NLg//+ANKj///4NKv4NBDhMCBgIcKOIIACDhFvBoYcHL4IMD/wNGgwaE+gNGjYNE6A2L/yrGGwv5SxAAD8iWJAAWQBo0PGxYABGxYcF8DCJBoWABpIcB/r7LSxAcFL44A/ZgxOJZghrIhbME/DoMDo8BBorBHv4OGYQsfBo3+BokDBAWUguvHQ5wBbQcbBwPAFQroEAwIrEgQVBEYkv//wAwc/EYoyCK4aABIApPB/gUFPQo6BEgcP//QBwpPFEQrCDCwYcBI4qmBMogcHKAK9DDiw5BDgpWMOY4zFSBytNeoSeGZQjnGKoJkEEYX5BogyFFYX+qEBt4FB/AyGAAoqFS4IOGLosBBoydDQYgAEHApREBpQOFBpEAgwNC0gNIAAMFqgMKAH4AxmgNMg6nGitVAwm/BwsD//wAwcPfo0//4FDgP//gcLCgNADhQUGA4+/CggcHI4PQDhZHGDg0vMgwcFAoKQGDgoFBAA4cFABAc/DjQAHaQ4AGSAoc/DlsvDhgA/AB+QBpkf8AIGqoEDgSIGgO/A4ilGgP/A4kH/4rF34kF3/9Bol/DgsP//AXQocF//8CgocFj//wDlEDgpkB+giEDgztFNQIcFEgIFDHARlBQJAwB//DDhRxB8CYFn/+FQn4CwoFEAgKVBDgwFDIgOADhSGBYAIcJCQKjBDg6QCN4YcFSALKBFQPQDgx8BKIIJB/AcHDAIrBW4YcFBQXgRwL5CDgsLaYZLCDgzTDUQYcFgIcDFQQcGcQQIEDgorDRwIcIRoQ4DDg46CoAcKgFlGQwNFAA1VqAOMAH4AWgyIDgEpBo0bWYcAg/9BorSBbwS7CBw2/YQgUB6ANEg68EZIIxEXg4FBJwjZC+jfLCwOAAoV/b40C//4AoUL//gAYRgCj5lEMge/JYRQFPIYcEQQoTDDgYIECYgXEDhP/UQYcKUQRWFCYRRBW4RWHDAMvSgYEBSAYYCUQKUCVopvBDAKiBBIQEBYgYFBwAuBJgjEDEQP+eAJlCJgjQDAAYrBEgJpCCgQAE6BVBMgYxCAA5HDEYQAGd4IrG+INDFQkAKgX4PAIACBoi0CMQJbDXQYACjWpe4Q4GAAsBBwINKAANZMQgA/Q4YNLgTzEOZCdHAAqBBDhbdCBpUvBoIcKZoIcLh4NCDhL4CDhUDBoYcIOAX9n4cJDQQfBDhB+B/9ADhIJB//ADhJ+C6ASCPxIYBDhELBoP0F4Z+I/h2DDgxwCJgipISYgcIAArGJAApACDhKHCDn4cLbo4LJSBQc/DhoA/ADMB3oNLg//8CKEAAeABAN/QgiKBAAX4UI4cFoChHDgn0DhoICl4hDDgoXCgQhDDiNVq4cDgJbDH4hREj54DBQZREDlZWBDhZzHDgwEBOYoRCVogcJGgTKHGgX8A4MHZQwFBKIPQBAP//wcGNwImCQIISCDgkPPoQHBF4Q/F3//8AqBQIgcDIYP/8oRBMgYcEAYL6GTYoNE4AcHhYNDFQgcEOgIABOQiWFIoIABXQYcCMAKDDHAoAFgIdByANJAAMUBhYA/ACtrQAOkP5K6D/INHgTXE/oNMbAopGAATDCAAd/BwzZEgEfBow6FdAJUDq4DB+AOEBof4gEHFY0vBYO//wGBh4SCFQn9BIPAA4M/AgYAB3//oJvDNYP8BoYZB8AtBA4nQQAn8FoJRDv5lEGIOAn5HCIISRDDIQIFCYidCBAoTFhYFBDhe/H4I8BA4SRBKwZ+CKwu/OYh5CLIQWEDgsCRYYhBVogKCdIIrCUwLKDEQbUBAYKjBc4gcCNAP/yFvaIK7FDAJIBAAbYEDgS/BAAYqEDgYrCAAIqEDgZECAARVDgEFUYgNCQoQAHBwSrDAA9v/wbKAH4ADVIINLdoKlEDl0gDhkfDhkLCwYcIfQIcLg4WEDg8CdIIcKBoQcKgINBDhe/Dhl/BoP4DhINHDgsvBoP9VpMfBo4cEBoX+ZRKaBAANADhCaBBo4cDBoeABoocCTQX/4DeGDgKaD6ANGDgQNC8ANGDgSoCBpAcBAAX0Bo4cCBpYcDWwgcIVAocHBpQcCWwwcHBpQcCWwwcGWwwAFiobLAH4APgO/yANKgSWB6AKGjVQDYLeC4ANFl//8EA34OCBosfEwQRBAAP8BokHBIVHAYQiCKAYIC/oNDFYrZBAAf+AQP4BocLBon0EYRXEBohEBd4P9Kov0KgQHBh//+CKECgN/RoZ2BQAuACIJvCFYIcDAoYmBoBeDAgQFCEwQXCEIP0DgiIBg/+KAmADgYKCn6aCOgKCDDgYmBDhIKCl40CDg5EBZoIXCDgJWFAoJzDKwp+DQoKQCGYaQD6D4CfoaQDZQXWcYjqBBoabBAAZpBFQIvCYQYAD6lvJgZlDAA6BDNYQABx4NDI4jzCG4IDCfoQADS4J7BPAIACR4amFhYNCKogAFHwQ4FAAqWBVYYAIgtQBpYA/QYuqyANKfwLmCBpabKXgTjEtbLF37VFEYIhEewarDv/+BocDBof/4AcCJogKB/ItBFYQcFFQInBv7lCDgsCDAYgBoAcGn4JCDAP4DgwFBEwMAl5ICv5zE34FD//8gELOYkPC4QEECIQXDGgIhCBQIWEAoSpCE4IcPJYIWCDhCmBWIRREDgiUBBoZWGwACBXYqWCfIP0FQKBEGgIxCUYKwCMgYxCcYgGBI4j1CFQX9dQLJEc4QHBBYIACFQgyCAArRCbIgAFTogrDAAoNFK4QAEVYY6JIwqNDDZYABt4MB/IMIDwVVBhQA/ABEP//4AoTOBQgx/Eha9HDn4cWgtVqAFCitVoCNQA'))),
        46,
        atob("DhYoJicmJycmKCcmDg=="),
        58 | 131072
    );
}

Graphics.prototype.setFontCantarellSmall = function () {
    // Actual height 22 (21 - 0)
    // 2 BPP
    return this.setFontCustom(
        E.toString(require('heatshrink').decompress(atob('AFf///9n8Ah4FB8fwBQoAKhf/Aoe/DAIKHCrQLB4H4AoW8h+ABQxMBAAOAK4X//gKFEBUFr/V/tUConAEAtV/oRBoBBLg/A+irToEFPIcD8AEBj/8j4EBgY/BQoMP/t+h5iC4fwJgX8n4XBHYPB/abCnsP/wgC6F/4AxCgOQIpkb8gjBXQXQgQmB/NvHIJBBgPwEwX//0vK4JRBz54CgtHRAcC/ptCgP/p5RBgF/wX/FYMv6E8h4rB+ED6IKBDwMvLoMNRQS0BABkCOYUuoLQCPgM/L4TaB6G+gCSB+iwBAIN/wE9gE+CwLjBMQP3/ogBj/9fII/Dn/QGwQSBHgY2CAAM/x6wCh5pBBQU0gGALRSvBAoe/bIQKGACNv/7YBEIJ0B/oEDAoN//K9Bv/zZwSsBigeDkAkEBQkjCodvEAZQBFYg2FFAJBDABVBAgd9XAIABg/7PIcvUQn/9qyD//gBQbwCZYIVDgf7B4UAv0+GIeCoCZOh7JE/AKSg59CWgheBBQoraABEf4ARDOocB/5qDjxvNhYeDgG8BV4ALg7tDgF/BRIAFtxyD37oCVYP9QwX//K6D8gEBXAKeCh/+EQf0IpUFqAECl//CQUPcAcD/+q/5uBv9AgI7Bh/QK4bBCn7ZDgQKHLIMLAQN/wECEAMCGAJTChYEBNgQFBAgQAQLYYxBJ4LBCHgTBBl9ABQUD+tVqoKBn48CBQIECDAIKEdqcGWIQAOkixCSwJrBTIQiBHwJcDWoRDDUgUP8QKB/EC/EvCoV/V4X+j/ABQMHbQIKCn6tBBQMA39ABQTzDVKMQAQMcFYLxCLQO9cwnA0kDK4RTBfgf4BQZMBBQXD/h4C35xBJwK6DPYMf+p9CHgMH/BOOgzoBAAMDCocC/7ECgP/BQe/74KCv/gBQUv+hUBJgIIBBQRGCXQQECI4IKEAARMEEAQAC0ipRgtVqECUgIpBoCOCbYKZC/2/V4eC+DbCfQQKDCof4j66DwP8hYrB/EP/f8J4V/GQIKBRILjBAAVQKhwPDg//aoLWDSgm/EwM/99ALIMH+fwJgW9nyyBfgXgMQX8KoJiDKYJXCj//K4VAK4JBD37xDABC9FDoIKD4ADBuAKDv4KDl5BCAgJoBBQMfNoX8j/+EAXLAgTQDBQQEDBQI8DIIr5NDgVpUoIEBl/5PAQIB/+vUgP+v/AK4XBeIkPUgeA+ikDfgcL/f9fgSdBawT1Br5UCgKqBfggAO35pDYgW8PwX8hfAgTWB4AKBHwO9UQMD8ABBNAL7BnpOBL4MH6f0L4OA/onBJgIABZAJ+CLgMAjf/8hMNn9AHoMAgf0gLvCBQgAIUoITCn6aBCYMHR4QKBvI2MF4YxCTwbgDAAP/NgIABj+fIAR5BF4IABv0HHQKfB4BTBFQP4LggMBZaSuB/AFCn0PaIQKxIxRrBMQT0BAIIFB/jMBSYXgXwJzCOQcB/KqDh//RALTCSYQsBTwbWCHg4YDgEvIwxhDDYPP4BhBg/8fwUB/+PBQP0v4iCl//XwblEgX5Yx9v/+QAgO////KYM/AgP/NgIgBhf8gX9g2kj/Qn9DGQN/RoIUB4fw/kvyP+j9PA4JlB/H8MYMvh+P4fQgPx+gKBqt+BYPDEAPz+H9HgWJhfxqtVPATIBhfAgSzBgQKBXIIABP4J+BP4cbQggAMuADCgO/Sof/XoUH//4EoalCGAT1DwQUCHwLdCBQNCBQV/CoYbCYwYmEGIT0DHgJLDgOwLp4AGQQTVCAgQrBBQtAnkCBQP0gfALAIKF/EHBQfA/jbBgG/3/gn5VC/9LVQMf/X/X4MAig4BIYcaYgIAWFgLVCgYxB4BoEAgM/6EHGwMHJIMfCwO9BoO+K4QdBBoJJCK4MPwAKJCom8BQM+FYIoBAQUQBQMYMKy6LBQn4CYKvCJgK6DBRJXFJgXggF/BQP9L4ICBv5lBj4wDBALKDbgP5Yi5iRgfgK4c+MQYKbigKCACpMKBQo2BCoQ2CNoQKa+hNVt66Dn7FDKQRRBgTbB37bBv9AgIHBhbxBhY9BfgvAlMDUhn8BQIVBhfAnxeCv0D/4rBgfQIQI2BiAKBWi6vLBQg9CC4e8AgYKfeJ5inABkaAgbFCAATFBBRDFBAAUfYoIwCYoI2DoAKDwDFp6AWCgQ1CAAO/IAJaC7/0CgXwl4WBgf8CIJMCDgP+FYLJBg4rBFoUfgEMEYVwJQcBYtSvEgQKfgOgKS0/I4XAgYECSIIKGVwcHAoqdBAAULAov4AocffgcPYoQPBaAYEEEog2FJh5tQqoACYpn61WqTIN/6AbD35bDgJHEgRyEg5dDEQJ4El7KEn4oBfhQKEACMb/xCCEISUDRAQmBoA8Cj6LBn9AgS4BgKZCDoSkB8AFB3kAnzCCBQJaCCoQ0BCoIdCgYjBb4KFBCQN/X4YIBM4SOB/7xDACjxPK4JQBCoJXBLYJJBBRXwLYIrCoTKCJYLhDTwJ/CagJWUg3/yC6EGITgEegMHLgMHQwMPfgO9BoN+UwRPCgBKBikvBQOAg/CBQIdB37TBDoMD/YKBv4HB/odBAQN/EYMfHYIHBYoZkC3/+j50CAANQYqxnCNAKTBdgYKFwBbBAAP4gT7CBQQ6CBQP+BQXAn5RC/0L/57BAYP8v4cBeINAT4W/yEBE4QABg5cWcwNAg6OCHQK9BaoPwZAV/v9AV4XA/jFC/hTCBQV9BQYDBBQc/pfgBQMBXQUL6CQBwEAshkBB4IACiBLGgLCEnwEDgYYEBSC/C/iZCAAPABQoragWQWS4ABIIX0JgguBJgdAHIb3BAASiBAoe8AgcLBRIVEgJtBitVq2/oA2DaAI2CGAMBqtVqhXMPokPLQIAC//5AgUG//+LYTwBdYQABv//6AFCj//EYhBBAAMbBQdv/6nBgO/QQQrCGw5BFJggAKggFEEgYgBGgQABGoPkIohpFK4lvK5EvEQZyBK4J9B/pXDbwcPcYiTFHgJCDFQISDHgI2DgQ2Dg4KDUYJYCTAZiCFYUPOYhlDQYwAO4EDEgV8gE/OgQKBNgMfKQICBhZ0Cn/3KIaDBfgSEBfZELR4cH/wlCOANAn7pBn4eB342BDwMB/kAmCEC4DxQTYaDBH4a6BDoY2BKASoCOgRMCV4pYCCAIKCYYhsBDQZUBGwfgGwZkBACb5Cl4gBJYMLGwIKBgY4BBQI4BBQd/14KCl/iBQUP+ggCw/9gQKB/IeBBQR4BBQX/KQIKCKQIKCZAQKBhSRCUQgAMFYIAONoS5Gl4KEGQv/yArE8gFCYgP5AoUG//+XgUB34YEt/+EYcbYYkFK4xBJJgpnPRSIAJgIxDgF+Agcf6AECg4sEn/AAoe/AgcCBQgAMVArmBBVwANvC6EOQZtBFAn0CAhtERwkCDYgALoEfoBKCgf9AgMD+G/K4U+h9vBQXg+oKEj4VD+IKCn//3zWCeokHAoJ4RD4IAB4EDAgX8BQj/C/EA3h5CwEHPYQKBviEDhYKC/sBBgJBB/3/OYf/8A4Cv6hEABMBqClDM4cA35RBAgMf63+QYYBBaIbxCTIL8DnwKJBAIMBGoJPBG4ZGKLghBBRAUf/bbD+kHGxHQgIKCnoXBIIYKCVwTQBh4ECBQwAMhf5AgTxBWgQcC6BtCz9+GwXx+ZMDj5MD8PxTIcfJgS0B+QKCJAKOCEwPwcAQAKlIEDPAIECj5iDKAJtIh/DCof4RwI6CwYKIhY+NaAwUBaAReBIQP9gfwgX0hfwfQc/gXwYoIDBBQcvCoIKD3wIBLAXQgYEC+geBAgK7DABrxQGgIWDn6kEMwIACYYYKBHwLKDEAYnCEQUBPwJLQgH8MQTFCEAYKEWRTEEvwVD//fEASJBBQf+R0MAg/QC4mASgYvDh/XYgSOBj6bCnqmDgYZBRwUgA4KORJiIAPUgkDaAkv1WqBQT8EeIr8EMAQgHj4rDgIKECoogEFZfqIIUCEAkLNokBqtQNpkKMQLGCDQP8EAnAAoO8CocPbQcA+gKJDwQKCEAl/FYcA34KDABUC/1ARIf9YAg4Chfgl44CFIIrCIIMLFYX4LIcP4ABBAoP+gIMBgEH/3/GIUv//QGIV/NIgAOIwK2CcwS2CEoIKD8ECYoTbBj7bDgIKEl4KC+kDBQUf9R4DEgJyCdgL4DgJbCABaZBCoa0Ej/rFYQ2Bg5BEn5MDK4pMDBQhtFPAiDETKYrCDIgrCBQQiEIIIACIIIKOABkEAYV+gbxCh/4EQSpB4Q4Cn89PAfT8IKCBIIKD8P3RwcP/wgC8F/V4S7BJBEpK4g/CIAJ3B/DwDawQKCQYfQQoc9boIKDYoYKBlx/QG4Y2CG4X0IQhdDgH8AgcLBQl8BRImCEAWAFYYgCFY4AHQYi6B8gKDJYcAg3//KpD/54CAAO/BQe/BQQVBIwQgBEwc/GIcDJ4RBHoBBEyBBEcAcLI4hBKAgIKCB4IVCgQgEIIv+G4cb/4LDLoIrJv4KD35tCO4LgDn5LDgYEDgE0f5gACZAMIaAVAgbQC/sBbYUL/G/SwUfKQk/IwZuBKwn9B4ffJoUP8EvFYRMBvgEBho+DABTQFTIpACg7FC8EHIYMH//rIYRHBW4YLBDoSwBdAUv/67Cn7ADYoI2DnKYOgYoBPwU9ZYIKDj4KDJoIKC6f+BQU+/8fMQeBBQRtBBQf0gIKCni2BHIlQIQ8BeQkvSocfNAR7BAAP9QwVf//4v/poEW3/fVAd/aQSbBdAYARh4wCAA37AogVFJ4cv/iiD/f6NYNa/s///1DQOAv4fCKAMFBYIYDDoZzBbYQAVigeE4ApIvrwEQggVEgF8Agd/EAjDEiBAOg1VAAboEgrzG/kwBQUwmYKEn/wCpAKDCoIbBBQQbBCo5BIipGIgA='))),
        32,
        atob("BgYJEA4QEQUJBw0PBQwFCQ8PEA8QEA8PDw8FBQwODAsWERESEg8PEhIHCxIPFRITEBQRERASERsREBEJCQcMDAoMDg0NDQwNDgYGDgYVDQ4PDQsNCg4NFQ4ODQkHCQ4Q"),
        22 | 131072
    );
}

let lightWallpaper = require("heatshrink").decompress(atob("2Gw4n//2V3uF7uNzuFj2ezt972N/M73uNvt9nVE6c9u9N2tF2lF3EzzOZzndACHuABnr3YAyK6hZ/K7IAB7xaNK/5Z/K5PMAAPNLS5ZN9ZXvLP5XZAARXVOIPeLRpXnypXHLKnJD4IEBLOeZzhXJAAPNKx3cZwOZCYhZN9ZXvLJ/VK4WdBQpZuzNcK5oACK5XZK4WcBg/eLRqvtLJvJV5JZuzJWSAAXNK6gACLJvrK7FVK6pZGrJXCMQxZuK7AACIYJWCK6AAB7xaNK+AABK6pZjrhXfypHD7mVXgQANLJvrK9nFK4WcV4dZWyZZcK6nFrKfBAAfJK4YHC7gHCzpXQAAPeLRpXLGwYAQTwRvEK44HEK6RZaf6hOGJ4hgDK7IACLJvrK7XFIwWVW42ZW5PNLNZHEqtVK5oPBrJXEJwRXEL4a3D5hZX7xaNK4xGBqo1EK5RpFK5YbGLM7lDmc1K6IQEJwS3MAAnNLS5YMIwczAAM8K5auDK4ZfBVAOcL5ZZqEwXDK4+VWwxXJA4xXOAANZzhbW7xXKyZXCHwfJmpGBK6nJK4S3EAA4QCrizXLIwlCqZXG4pfHK45fIrJXOM4qyWAAJXKGwa3HUwa5EAwwQDfAJXOyoHDLLQdCJwUzEoZXNKIJeHW5BXQAARZXewROCmoiDW4Y+D4YGBLIpXLIglZLovJK5RZXTwRXHW45fDCIJXSZAJYF4pXCzi+K5pXUTwUznKFDW5ZZHI4ZOBL5JXEV4ZXLLKYTByZXGW5gAFK6IHErJXCMAgALK6GRiJPFK463DABBXLL5JYCK6BZOBwNRiIABibWCfwZXQdwZXRA4wAQ5pXK5JWCAAMZzmVI4/DK5YtDqZHDT4QGGK5QOFLKjRBK4gADI4c5W4oAHX4YQDmpIBrJNDJAi3IrI8BWiRXQAAMTIINVKxZXFBIpWEK5q/HW55XEypXKLIgALXwXM5IMHK5YHLBAK3Q5pXByJXMAARXLng1DBxKmIW5pWBzOcLBwTBK6C0LK50zmpXPV4gGBK6VRK6JZJnIhCyZXTU4a3QK5hWTAAZHIqZXPmZHDUAPJW6BXkWgo+B4pWKK4nJA4ZJByq2EK+ZZEqpWLK4hoGKwj+EMIZXQypXbAARWMAAIxCyYLHK463HABmRsxYeWgYAJrPM5K+LK5BWP5mWswABsJZqqtTMxc5K7hZFLrhMLABU8IIXFK6k2K4gACWby0MABFcK4czmpXSKw60GLNxXD4a3GK7BZhiJXPzhBCyZfGK7QACLNpBDqZXkWkMTKxM1K463DK75ZhWhBXEW45XhAARZlnJAC5JfHK8i0hiZPCnhAC4pXuLMK0BrhAC4a3GK9IACLD2cIAWTW4xXsWjxXHW4ZXuLLcTIAdRiJXBL4ZXwAARXWipADW4/MytZK+C0WjI/C5IIDKwi2NHA8ZqJZxiuZJIJXDW4lRK4M5K6NpzOZyy0gLCA0BzORW5U1K6IhCypXgWiE5GoNRK5S3EK6GZK8RZPrJWDK4nFA4xXNsJXoAASzNLoY7BzmRK6lpK9ZZQHgZX/AA1hK59RA4VcK6mTK9a0LiZXDmJfEK585DIWWK9xZIjJXDW4+cK5gRDK+IABsJXQLI5X9WghXDypWCipXFAARXCgxXIixX1AANZHgWRW45ZHgEALIVjBQZW3SghXPzJXBAAVpK/+ZyxXUhIICypW3sJGDqwHBiJWLV5OWK+9lIwcWW4wAHypXErIJCyAGBK+qUDzIIDK5eRK4gJDK4RZ1K49jK6swBIkAgxX0yZfHysRfYZXGgwJDsBXFWmJPDyxXHi1msJXEqJIDgoJDBAcDEAJZxK5eVA4SwEsxGDhJXHAwUQWYsGLFRGDAAUZfwa3HK5GRA4UBA4WQK4q0rJAKuDK4i3JIIYREL4wHDVoOZmBZsLwxXFnK3EfwynEW44QDWYsGK9VhfwYACJoZfBK45PDW48FM4wAELFI+BVwZXJeoIADsC3NK5BZrAAhFDqxXDgZXEVANpK44IDK5R5CK1VjIoYGBTwwAIiAQCnJXPWladEK6JDDW45Z0K5IJEK58wK6AABgxXnyZXEzRXOgwHDsBXSWkk5HgWWK4uq1WpKw+WB4UJW45Z0IohXHLJGQK8DPCK8sBKwYADK5eRK7S0csJFDixXDhJXHWgZXDjJfGLOllK4YHCK5gABsAyCW44AegxXUtJXGolAhRWK1IwDK8y0VK4eVK4dEnRXPAoIaBW4ZZ0jJXCyxXEzRXK0YqCgZfHAEsGK5rsDK4lJKxWq0AoChJXtLJxXHzKuL1WQK+YACK5s2A4RVLK4tqA4WmQ4mRWmRXDA4ZXNylAEILADL4YICyyzrLIs5K6tEolAK48JAwOpK9YACJ4VpKwOWK6oHDmAkCnQHGAFi0BtORW4hXN1JXBUwQABEQa3HLOBXS1WZjJeGoBX3AARXSWxFEowIDsBX0WgZXU0JXCpIIDK2wACK6mgK4y3BoBX/ABmUK4VKA4WjA4VEK/5XOtS3GLOxXUwhMCzRfGAAlAK/4AFJQZXMWmJWT1KhDBAc0K5RZuK69BBAcEK5hsCK/ugIQVJL4wAPK/ekH4VKK6xZnK6eUHoUKA4WoK6gABoBX2mg7CnS3GACxX0gg4CzS3GUhRZsK6Y2DA4ZXMNAOQWZxpBK9upGYYIDshEKpIXFABxXs0ZGFW4oAHhS/PoGBghZbK6WkK4yfEoEzHwlEzRXPjS/HoBXrpRXHJ4I+FK59IB4U0Bg5XlHweKA4WgW4w+EDAZHIDAyADLK5XWTwa3HA4aeD1UEK5QYDPAYAIoBXNu5XRI4ZfHhQPGTweqIxcaV5pZQu4ABvRXO1JGGW54XCABIYDEAYANK5gACLB05AwjmDW5ehIJYYHABFGmy0MK4q0Re4q3InT2HpGWHwoYDwhWKoDAByAJGK5hZT0cjdoeqgj2KpAGBHwlDO4oAJaAWpBAmJzIgBK5gACWaQ+GW44+HZAZHFAAzQDihwFC4dAK5i0TEwoIDmi3GkgHCpRXPaA54CFAhXOWiWjTwwuEA44+D0RXLaA63DA4ZXRLJ+gK44uCW4juDTwekKxVGDAcEW5RXTAAN6K5Q+Dewa4DA4j2LAA54EDBZXVWhYlDxQJEzEJAwj2LK5epA4TQEwhXbWhE0QowAHHwdIew9JzOQK4jIDDAdDPA5XaLIxXDKxWq1D2LLwzQE0a3L+5YcAALuEbogAH0ieKIwYfCaAoQDDA9B///LL6GCFoYAII4YQDTwYHD0C3GXIhfD0xwDK4IACK7l6yUDKxZXEnS3GhQHC1D2DDIgJBX4bQFK4i0hK5SVCSwg+DL4avDoZ4LOAhXGWj62CGw72HW4ZfHU4hXLzRXJLMC0F1L2HwhfKpRXLEIeqK5YAB+60hGoaeEL45XDhRXLCIUJK5y0hvWgK5VDK4+aK5mqzICBK6C0f0j2GW5AQDK5wACK6RZdIwcqHAWiL42q0IHBpBWQK6oACK7FxJ4WXAwKmEhRCEylEnRXpWjF6glEoenA4RNBAAJPSK8K0X1ODVwRXFzRX2LKwAEWwIABW4JX3AAP3Kyt6KwVABAhX2Wi15K4VJMQxX3WidzK5IACK+5ZRuhXCpQPKWh5XnAARXM0hXCg5qNK+60MuBXCy7DOLJZXsWhV5K4WnK54ABvRX3LJGUolJKyK0JK+IAB+6ZEzKuSWhJXzWhJZZK+y0GADJX4LLxX6AARX/WmJX/Wi4"))
let darkWallpaper = require("heatshrink").decompress(atob("2Gw4n/kHCgHKwHS4Ha8tY4PJ81IoHK80ggHj81A8tg8Hi8to8HJsHKu93uFEAAtmABtq1QASxAAoK4N9K4xZQLCZZoK4MLK5BZk1BXo2hYKoxZ/K5Pb3e7LLVqLOxXELP5XTuBWDAARYKohVK7u2LKxXgV4hZX6AfBWbBXdvvd7pZZtcHu936wJELCZZbK4YABLA5ZPsBWBu8GXQxZtu8NK4ZZJ2hYKoxXEvZXGLKuoK7xZV25XCuhXILNd3Kw4AB7ZZR65XCgxXKs1qLM5XKLKUHK4XWK5ZZWK6NwK5ZZKK5PUohYNLMpXOLJtNKwVwL4ZZxvpXPAAJYHLIJXIpsA7ZZNLCZZMhpXRLIS1G2BXCvpXDg5eB6izOLCeoK73Qg9wLAhXHW4cEolGLNddK6aeBu8NK4fXJ4ULK4VAA4V7A4RZOtRZaKyfdUwfdWIRXE3e0oi3HLNRWT6BGCuAHC7a3Cu5eCW5AADLBpZVK4xHBIoZXR7pXHA4cEK4xZCshZiHw0NK5aeDvoIDL4ZWCK4nUK5CzQLCY9C6o1CK7PdKwO9A4S3CLBRZhewxGEAA6eDNAYYHK4a3D2hYKo1kLLqeLqC2GK54HDK4ZZIpsAhpZCWbg2Cq5GG6r1DfwwQEOAZfIK4hZGCAUEWYZYNtRXWHwddK46nDW47QE7ZYGLIYYCvq4ELLI+GJ4aeLXIgYDM4YYG7ZaHpofDK4gABLBpZJTww+DW5YABgHdgBeGW5BZBK4u9K5RZXFgPVHxa3HAA4YIA4ZpBhpZE2BXMLKBXKuo1DW5ZXMDA7ICWwJXCaAd93ZYKoxZRewpXDW5gAHvpOFDBAPD3bQDK4O72hZbTwpXYT4JXKEBcLW4RZbK5K3HewhXlLLSeGrpfFGwa3DABAXC7r2Du5fOu/bK4oABLBVEK5g/EVANVA4g+GABCeHXAYHDvq3JLIO9gENLLCeNHw4AHexAABgEAAoZXDW5DICWwpZSK513gpWLYwT2GO5RXEW46wE3vQhpZQexoAPHwZ4MK4amCW5F9K4YIBuHb2hYKoxXDq5XfPBj+GK5IGBVwLiCW4RZNK9twK4ZGCDAhfH7q3HLJdVK8A+DK6AIDA4cNPA1wK4ZZLqodDADF1HwwPL7twBIZQCAwxXEV4gADK5BWbAANd7vVM54QFuEAN4hXDaAbYB7ZZNK7w+GBxCeGABC/DEIZfDLA5ZEK7wAPTwxnLK5BZJ2hXBq5XtH4PVYBZXIKwhZLK9FwAwsAKxd3vpLDL45ZMV9wAOK4fQK5vd7ZXEPxgAwhpXSLIpAmPyxXD663GLJqu8u5DDK4ZfDABpX/AALKDK/4AOuBXHrpX/ABt1II5WQK/t9IAXVW45X/ABUNIAXQK/5XaW4ZX/ABddIAXXK/4ASIAdXW4xX/uAKKIAcHW4xX/ABV1IA5JEqBdMK//VW4/QWxojHlnCK/0HA4N9K6N5zOZy5YxUwpfEJAYHEK5pWBzOTK+MNUwinEW4ZXVzJXxuFVqBeGW5JXMuRX1AA1dI4XXW4xXNvJX/7tXW4xX/ABZHDK7OTK29wI4cHW4xXNnJXCy5X3upHHKxRXGKwRX96q3HK/4AKvpXGW4hXRk5X3rpGC6BXUuZXDK25XEq63GK5t5K/5XEhpXUzhW3uFVqpXFL4YAH6sXDQcpK4WSK+91K4IABg5XPiMRLIXJK4WXK/gIDK5fQK4IABu5WCK/4ABuBWK7tXK4cXK4c3K/4HBWAVVgFVK5MSK4ZW3K4lXL48HWwJdCAAMHK4ccK49zzOSK/wHCK4fVu5XDjJXDAwISBAwUnLGKmEAAMFA4VQL4ZXMyYHCiYHCy6wzVwZXEW4pXHnJPDL42SEQdyzM3L2ZXFL4fQK4nJJ4WRW44iDA4RX1A4YGCL4VVqJPBIwSnBK4UpW4cXDIN8A4ZYxVAKuDK44ABqJXDzNxiMXAwa3Ci95K+oAGK5FTK4iwBVwZXDW4ooJuJWsupXDg5XDrJXEAA0hK4XJV/ZXEWohXMKwURA4ZX/AgT/EK58xiMXK+sFK5E5KxWcKwUSBAdxBARX0KwdXAwiuLyROCji3HLOhXVyJMCjJXJiMXK/NSK5eVqpXFyZXGWWFwK4cHK4dTK5c1CoUpW4xZ0upXDWwlZK5cVCoXJK50Ri5X/AAIVDA4fBK5ZZrK5L2DAA+cCgVRBAclK5oABK85WDqAHEewYAHyQVCqS3FqJZ1K4dXA4dTKxWZyoVCrhXFLKMXK9ciVxZXErIHCyYeDAAKyyK45VLAAPFCoUZA4WRDwdSmUVLK8HK7gdDK5slCoU5W41RAwOSAoRYOi6viA4ZXNmoVC5K3GrIHCEoayPLLt1GANQK6JPDW48pA4xZRLDkFVwhXOyZEBrgHDJoa3HAAVRLNhXSzPCkYGEJgYHDmpXFLKMXK9wAFzhXHipXHAAKyuK6mSI4VSW45Z1K6mVIoVcW44AJqJYOi5Xv4pECrK3GLOxXUmpXGW4YAOLB0RK6/MK6ZADnJXVWSBZW5gABK6vJA4XFK6RZRi5FBg5XT5hCDABecHoYIDkpXUAAKyiK4ZZPyRXHKyxZjK4pZNyo4Cqa3HAC1RLB0XK508LA/MK5PFG4VcA4WTK7RZfmczLKM1GoVZW4wAbLB0RK5oABLBBZGGYZXjWSBZKK4ZZK5JXHnIHC4pXfLKMXK5pZMzgwDMAclIJZoBMyqyPLIxXHmc8LJGSFwa3HAA9TBwJvELMRXNLJKXEKwRHMrK/PqsiBJFRWSFxK5YABK5KeCzOTIpcpCAU1CBofKLKJXMLIo+DrnJIwOVHwuSHIgPCK5lSX5xYOiMiLBxZCFwdcAwPJK4Y+DG4gHCI5lcB4R4EWS0ikUjLB08HwcsW44+C4pXHIxdZK55ZOK4JZQJ4c8K4RfDHw63DzhELlJXRAAJXOLJ0yIwRWCK4ivHA4eSIRc5K6ZZKK4oABWBoDBK4S3F5OZA4b2QCwIABDAYAIqMhAwpXOLJoAD5nCEwS3DFwZXJYoYACB4WZKxgOByIJGK5xZQniPBlhXHlKeHU4PFAwdSK554DBAkszMxK58ikZZPKwfDew6pDHwWcB4dTB4QIEAA54DEAZwDitVK5xZU4Q2DAwKOFHwYHDrgHCyRXLPAbQDW4ZfCqJXOAAJYOmfMe4i3C5IHDnJXGHweVK5YPCV4h4DGIZXQLKCFDqRXC5g2DHwa3HK6C3HDAf/LCRZNJwdTK4aGCqY1Czi3HOAYAHqRXHA4avD/4ABLCUjK5QtDrhXDWAU85g1ByaWHOAYAHrhwHK4YYDu9/LAPyLLgtDqczKIIAHyT2LqRsCAAdZB4QYDW5F3AAJZFl5ZXEoYLDK47lDHwaeEW4RXMW5BXCAAJYB/6ySkRXJBIpXJqaeKB4dVnIICya3LK4hZcmolCXQxZEfAdcU4WVTwwHDW4a5EL4YQDqZXGLK8jWAgFDAAs8K4JGDrgGBU4ieDK4hWDBITHDCAlZK5F3v5YB+RZWABc8IwcsW4THCK52ZzheGK5hZnIwa2C5klA4UpIwS3DU4gAHK4cpK5YABLAP/LCUiKxcyK4ZWC5gHDnJGCW4dcK5eTX4ZXNLMRGDqszKwPDL4vJzK3DrJXLCIRnBK55ZXkZXLqQGBnnCW45XRzPMAQJXRu9/LAPyLLJXDqZfHK4YIDnJXNAARXSLLpXLqZXD4oICKyBXVAAJYBLKhXT5gHBrnM5JXmLIhYSLIMyJ4S3DkpfFK4XDnhdDLJxXYLLBQBVwczKwVVkYHCKggAELJhXau9/LAPyLCRNDK5JZLK8xZbmRXDKwhZVK7pZYmc1K5fDmZYI5JXmAAJYB/5YSkpXLAAZZOK8JZVK4dSK5cznhZMK8d3v5ZRK6JZLK8xZE+RXRkUjLLBXmLKBXDA4ZZPK+AABLAP/LBRXGAAJYOLIxXqLJshKwxZWK9izPAA8jLB08K+F3v5YB+RZjK95ZnK+IABLAP/LCUiK/5ZkK+pZXkZXIA=="))

// Draw thick outline - for time
function drawTextWithOutline(text, x, y, textColor, outlineColor) {
    g.setColor(outlineColor);
    [-3, 0, 3].forEach(dx => {
        [-3, 0, 3].forEach(dy => {
            if (dx || dy) g.drawString(text, x + dx, y + dy);
        });
    });
    g.setColor(textColor);
    g.drawString(text, x, y);
}

// Draw thin outline - for date
function drawTextWithThinOutline(text, x, y, textColor, outlineColor) {
    g.setColor(outlineColor);
    [-2, 0, 2].forEach(dx => {
        [-2, 0, 2].forEach(dy => {
            if (dx || dy) g.drawString(text, x + dx, y + dy);
        });
    });
    g.setColor(textColor);
    g.drawString(text, x, y);
}

// Drawing the watch face
function drawWatchFace() {
    let date = new Date();
    let hours = date.getHours();
    let minutes = date.getMinutes();

    // Determine theme and colors
    let isDarkMode = g.theme.bg < 0x7FFF;
    let textColor = isDarkMode ? 0xFFFF : 0x0000;
    let outlineColor = isDarkMode ? 0x0000 : 0xFFFFFF;

    // Screen size
    let screenWidth = g.getWidth();
    let screenHeight = g.getHeight();
    let centerX = screenWidth / 2;

    // Clear background and draw wallpaper
    g.clear();
    g.drawImage(isDarkMode ? darkWallpaper : lightWallpaper, 0, 0);

    // Format time and date
    let timeStr = ("0" + hours).slice(-2) + ":" + ("0" + minutes).slice(-2);
    let months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun",
        "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
    let dateStr = `${months[date.getMonth()]} ${date.getDate()}, ${date.getFullYear()}`;

    // Estimate sizes
    g.setFontCantarellBold();
    let timeWidth = g.stringWidth(timeStr);
    let timeHeight = 58;
    let spacing = 10;
    let dateHeight = 22;

    let totalHeight = timeHeight + spacing + dateHeight;
    let startY = Math.floor((screenHeight - totalHeight) / 2);

    // Draw time
    drawTextWithOutline(
        timeStr,
        centerX - (timeWidth / 2),
        startY,
        textColor,
        outlineColor
    );

    // Draw date
    g.setFontCantarellSmall();
    let dateWidth = g.stringWidth(dateStr);
    drawTextWithThinOutline(
        dateStr,
        centerX - (dateWidth / 2),
        startY + timeHeight + spacing,
        isDarkMode ? 0xFFFF : 0x0000,
        outlineColor
    );

    // If screen locked and setting enabled, draw lock icon
    if (Bangle.isLocked() && settings.showLockIconWhenLocked) {
        drawLockIcon();
    }
}

// Mark this app as a clock so launcher button works
Bangle.setUI({
  mode: 'clock',
  remove: function () {
    require('widget_utils').show();
  }
});

// Redraw on lcdPower and lock events
Bangle.on('lcdPower', on => {
  if (on) drawWatchFace();
});

Bangle.on('lock', locked => {
  drawWatchFace();
});

// Redraw every minute
setInterval(drawWatchFace, 60000);
drawWatchFace();

Bangle.loadWidgets();
require("widget_utils").swipeOn();